function c(a){switch(a){case "hydrogen":return 2.016;case "helium":return 4.003;case "nitrogen":return 28.02}}function d(a){switch(a){case "hydrogen":return 1.407;case "helium":return 1.667;case "nitrogen":return 1.4}}function e(a){switch(a){case "hydrogen":return"H_2";case "helium":return"He";case "nitrogen":return"N_2"}}
function f(a,b){a.g&&b==a.i||(a.g&&b==a.i||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,200),b=Math.min(b,1E3),a.i=b,g(a),l(a,a.o*a.i),a.S.innerHTML=`${a.i}`,m(a),n(a)),a.u.value=`${a.i}`)}
function p(a,b){if(!a.g||b!=a.h){if((!a.g||b!=a.h)&&["hydrogen","helium","nitrogen"].includes(b)){a.h=b;a:{switch(a.h){case "hydrogen":b="helium";break a;case "helium":b="nitrogen";break a;case "nitrogen":b="hydrogen";break a}b=void 0}q(a,b);b=c(a.h);a.g&&b==a.l||a.g&&b==a.l||Number.isNaN(b)||!Number.isFinite(b)||(a.l=b,g(a),r(a),a.T.innerHTML=`\\[ \\hat{m}=${a.l}\\,\\text{kg/kmol}\\ , \\]`,t(),a.G.innerHTML=`\\[ R=\\frac{R_{u}}{\\hat{m}}=\\frac{${8314}}{${a.l}}, \\text{J/kg-K}\\ . \\]`,t(),m(a),
u(a),v(a));b=d(a.h);a.g&&b==a.m||a.g&&b==a.m||Number.isNaN(b)||!Number.isFinite(b)||(a.m=b,g(a),r(a),a.R.innerHTML=`\\[ \\gamma=${a.m}\\ . \\]`,t(),m(a),u(a),v(a));b=a.h;var h=a.U;for(var k of h)k.innerHTML=b;k=a.V;a:{switch(a.h){case "hydrogen":b="H<sub>2</sub>";break a;case "helium":b="He";break a;case "nitrogen":b="N<sub>2</sub>";break a}b=void 0}for(const y of k)y.innerHTML=b;u(a);v(a);w(a);n(a)}a.F.value=`${a.h}`}}
function q(a,b){if(!a.g||b!=a.j){if((!a.g||b!=a.j)&&["hydrogen","helium","nitrogen"].includes(b)){a.g&&(b=b==a.h?a.j:b);a.j=b;b=c(a.j);a.g&&b==a.A||a.g&&b==a.A||Number.isNaN(b)||!Number.isFinite(b)||(a.A=b,r(a),u(a),v(a));b=d(a.j);a.g&&b==a.v||a.g&&b==a.v||Number.isNaN(b)||!Number.isFinite(b)||(a.v=b,r(a),u(a),v(a));b=a.j;var h=a.P;for(const k of h)k.innerHTML=b;u(a);v(a);w(a)}a.D.value=`${a.j}`}}
function g(a){var b=Math.sqrt(a.m*8314/a.l*a.i);a.g&&b==a.C||a.g&&b==a.C||Number.isNaN(b)||!Number.isFinite(b)||(a.C=b,a.O.innerHTML=`\\[ \\boxed{a=${x(a.C,6)}\\,\\text{m/s}}\\ . \\]`,t())}function r(a){var b=a.l/a.m*a.v/a.A;a.g&&b==a.o||a.g&&b==a.o||Number.isNaN(b)||!Number.isFinite(b)||(a.o=b,l(a,a.o*a.i),w(a),n(a),a.K.innerHTML=`${x(a.o,6)}`)}function l(a,b){a.g&&b==a.B||a.g&&b==a.B||Number.isNaN(b)||!Number.isFinite(b)||(a.B=b,n(a),a.L.innerHTML=`${x(a.B,6)}`)}
function m(a){a.N.innerHTML=`\\[ a=\\sqrt{\\gamma\\,R\\,T}=\\sqrt{\\gamma\\,\\frac{R_{u}}{\\hat{m}}\\,T}=\\sqrt{${a.m}\\times\\frac{${8314}}{${a.l}}\\times${a.i}} \\]`;t()}function u(a){a.M.innerHTML=`\\[ \\sqrt{${a.m}\\times\\frac{R_{u}}{${a.l}}\\times T_{${e(a.h)}}}=\\sqrt{${a.v}\\times\\frac{R_{u}}{${a.A}}\\times T_{${e(a.j)}}} \\]`;t()}function v(a){a.H.innerHTML=`\\[ T_{${e(a.h)}}=\\frac{${a.l}\\times${a.v}}{${a.m}\\times${a.A}}\\times T_{${e(a.j)}} \\]`;t()}
function w(a){const b=e(a.j);a.I.innerHTML=`\\[ \\boxed{T_{${e(a.h)}}=${x(a.o,4)}\\,T_{${b}}}\\ . \\]`;t()}function n(a){var b=a.i,h=a.B;a.J.innerHTML=`\\[ \\boxed{T_{${e(a.h)}}=${x(a.o,4)}\\times${b}= ${x(h,6)}\\,\\text{K}}\\ . \\]`;t()}
class z{constructor(){this.g=!1;this.u=document.getElementById("T");this.u.addEventListener("change",()=>f(this,parseFloat(this.u.value)));this.u.step="1";this.u.min="200";this.u.max="1000";this.F=document.getElementById("select-gas");this.F.addEventListener("change",()=>p(this,this.F.value));this.D=document.getElementById("select-compare-gas");this.D.addEventListener("change",()=>q(this,this.D.value));this.U=document.getElementsByClassName("selected-gas");this.P=document.getElementsByClassName("compared-gas");
this.V=document.getElementsByClassName("selected-gas-symbol");this.S=document.getElementById("given-T");this.T=document.getElementById("molar-out");this.R=document.getElementById("gamma-out");this.G=document.getElementById("R-out");this.N=document.getElementById("a-eqn");this.O=document.getElementById("a-out");this.M=document.getElementById("a-compare-eqn");this.H=document.getElementById("T-compare-eqn");this.I=document.getElementById("T-eqn");this.J=document.getElementById("T-out");this.K=document.getElementById("T-ratio-out");
this.L=document.getElementById("T-value-out");this.i=288;this.h="hydrogen";this.j="helium";this.l=2;this.m=1.4;this.C=1292.7;this.v=this.A=1.7;this.o=.6;this.B=171.9;f(this,this.i);p(this,this.h);this.g=!0}}function t(){typeof MathJax!="undefined"&&MathJax.typesetPromise&&MathJax.typesetPromise()}
function x(a,b){a=a.toPrecision(Math.max(1,Math.min(21,Math.floor(b)))).toLowerCase();a.includes("e+")?a=a.replace("e+","\\times 10^{")+"}":a.includes("e")&&(a=a.replace("e","\\times 10^{")+"}");return a}new z;
