function c(a,b){if(!a.g||b!=a.C){if(!(a.g&&b==a.C||!["hydrogen","methane"].includes(b)||(a.C=b,b=a.C,a.g&&b==a.B||a.g&&b==a.B||!["hydrogen","methane"].includes(b)))){a.B=b;a:{switch(a.B){case "hydrogen":b=1.407;break a;case "methane":b=1.31;break a}b=void 0}a.g&&b==a.i||a.g&&b==a.i||Number.isNaN(b)||!Number.isFinite(b)||(a.i=b,b=a.i,d(a,b*a.u/(b-1)),f(a),a.L.innerText=`${a.i}`,a.U.innerHTML=`\\( \\gamma_{h}=${a.i} \\)`,h(),k(a),l(a));a:{switch(a.B){case "hydrogen":b=2.016;break a;case "methane":b=
16.042;break a}b=void 0}a.g&&b==a.D||a.g&&b==a.D||Number.isNaN(b)||!Number.isFinite(b)||(a.D=b,b=8314/a.D,a.g&&b==a.u||a.g&&b==a.u||Number.isNaN(b)||!Number.isFinite(b)||(a.u=b,b=a.i,d(a,b*a.u/(b-1)),m(a),k(a)),a.$.innerHTML=`\\( \\hat{m}=${a.D}\\,\\text{kg/kmol} \\)`,h(),m(a));b=a.B;var e=a.S;for(const g of e)g.innerText=b}a.K.value=`${a.C}`}}
function n(a,b){a.g&&b==a.h||(a.g&&b==a.h||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,-20),b=Math.min(b,5E3),a.h=b,f(a),p(a),b=a.h,a.T.innerHTML=`\\( T_{1} = T_{0} = ${b}^{\\circ}\\,\\text{C} = ${b+273}\\,\\text{K} \\)`,h(),l(a),q(a),r(a)),a.F.value=`${a.h}`)}function t(a,b){a.g&&b==a.l||(a.g&&b==a.l||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,.01),b=Math.min(b,100),a.l=b,f(a),a.V.innerHTML=`\\( p_{1}=p_{0}=${a.l}\\,\\text{MPa} \\)`,h(),l(a)),a.G.value=`${a.l}`)}
function u(a,b){a.g&&b==a.m||(a.g&&b==a.m||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,.1),b=Math.min(b,1E3),a.m=b,f(a),a.W.innerHTML=`\\( p_{e} = p_{\\text{amb}} = ${a.m}\\,\\text{kPa} \\)`,h(),l(a)),a.H.value=`${a.m}`)}function v(a,b){a.g&&b==a.j||(a.g&&b==a.j||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,.1),b=Math.min(b,1E3),a.j=b,w(a,a.j*1E6/a.A),a.X.innerHTML=`\\( \\text{Thrust} = ${a.j}\\,\\text{MN} \\)`,h(),x(a)),a.I.value=`${a.j}`)}
function f(a){var b=a.i;b=(a.h+273)*Math.pow(a.m/(a.l*1E3),(b-1)/b);a.g&&b==a.v||a.g&&b==a.v||Number.isNaN(b)||!Number.isFinite(b)||(a.v=b,p(a),l(a),q(a),r(a))}function p(a){var b=Math.sqrt(2*a.o*(a.h+273-a.v));a.g&&b==a.A||a.g&&b==a.A||Number.isNaN(b)||!Number.isFinite(b)||(a.A=b,w(a,a.j*1E6/a.A),r(a),x(a))}function d(a,b){a.g&&b==a.o||a.g&&b==a.o||Number.isNaN(b)||!Number.isFinite(b)||(a.o=b,p(a),k(a),q(a),r(a))}
function w(a,b){a.g&&b==a.J||a.g&&b==a.J||Number.isNaN(b)||!Number.isFinite(b)||(a.J=b,a.Z.innerHTML=`$$ \\boxed{\\dot{m}_{e}=${y(a.J,6)}\\,\\text{kg/s}}\\ . $$`,h())}function m(a){a.M.innerHTML=`$$ R=\\frac{R_{u}}{\\hat{m}} = \\frac{8314}{${a.D}} = ${y(a.u,4)}\\,\\text{J/kg-K}\\ . $$`;h()}function k(a){var b=a.i,e=a.o;a.P.innerHTML=`$$ c_{p} = \\frac{${b}\\times ${y(a.u,4)}}{${b}-1} = ${y(e,6)}\\,\\text{J/kg-K}\\ . $$`;h()}
function l(a){var b=a.i;a.N.innerHTML=`$$ T_{e}=${a.h+273}\\times\\left(\\frac{${a.m}\\times10^{3}}{${a.l}\\times10^{6}}\\right)^{\\left(${b}-1\\right)/${b}}=${y(a.v,6)}\\,\\text{K}\\ . $$`;h()}function q(a){var b=a.o,e=a.h,g=a.v;e+=273;a.R.innerHTML=`$$ ${y(b,6)}\\times ${e}=${y(b,6)}\\times ${y(g,6)}+\\frac{V_{e}^{2}}{2} $$`;h()}
function r(a){var b=a.h,e=a.v,g=a.A,z=a.O;a=y(a.o,6);z.innerHTML=`$$ V_{e}=\\sqrt{2\\times\\left(${a}\\times${b+273}-${a}\\times${y(e,6)}\\right)}=${y(g,6)}\\,\\text{m/s}\\ . $$`;h()}function x(a){a.Y.innerHTML=`$$ \\dot{m}_{e}=\\frac{\\text{Thrust}}{V_{e}}=\\frac{${a.j}\\times10^{6}}{${y(a.A,6)}} $$`;h()}
class A{constructor(){this.g=!1;this.K=document.getElementById("gases");this.K.addEventListener("change",()=>c(this,this.K.value));this.F=document.getElementById("T0");this.F.addEventListener("change",()=>n(this,parseFloat(this.F.value)));this.F.step="1";this.F.min="-20";this.F.max="5000";this.G=document.getElementById("p0");this.G.addEventListener("change",()=>t(this,parseFloat(this.G.value)));this.G.step="0.01";this.G.min="0.01";this.G.max="100";this.H=document.getElementById("pe");this.H.addEventListener("change",
()=>u(this,parseFloat(this.H.value)));this.H.step="0.1";this.H.min="0.1";this.H.max="1000";this.I=document.getElementById("thrust");this.I.addEventListener("change",()=>v(this,parseFloat(this.I.value)));this.I.step="0.1";this.I.min="0.1";this.I.max="1000";this.L=document.getElementById("q-gamma");this.U=document.getElementById("given-gamma");this.T=document.getElementById("given-T0");this.V=document.getElementById("given-p0");this.W=document.getElementById("given-pe");this.X=document.getElementById("given-thrust");
this.S=document.getElementsByClassName("gas-out");this.$=document.getElementById("molar-out");this.M=document.getElementById("R-out");this.P=document.getElementById("cp-out");this.N=document.getElementById("Te-out");this.R=document.getElementById("energy-eqn");this.O=document.getElementById("Ve-out");this.Y=document.getElementById("me-eqn");this.Z=document.getElementById("me-out");this.B=this.C="hydrogen";this.h=2E3;this.l=6.8;this.j=this.m=10;this.i=1.4;this.D=2.016;this.u=4124;this.o=14434;this.v=
352.6;this.A=7445.6;this.J=1343.07;c(this,this.C);n(this,this.h);t(this,this.l);u(this,this.m);v(this,this.j);this.g=!0}}function h(){typeof MathJax!="undefined"?MathJax.typesetPromise():console.log("MathJax not loaded yet!")}function y(a,b){a=a.toPrecision(Math.max(1,Math.min(21,Math.floor(b)))).toLowerCase();a.includes("e+")?a=a.replace("e+","\\times 10^{")+"}":a.includes("e")&&(a=a.replace("e","\\times 10^{")+"}");return a}new A;
