function c(a,b){a.g&&b==a.u||(a.g&&b==a.u||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,1),b=Math.min(b,500),a.u=b,d(a),a.M.innerHTML=`\\( ${a.u}\\,\\text{kN} \\)`,e(),f(a),g(a)),a.H.value=`${a.u}`)}function h(a,b){a.g&&b==a.j||(a.g&&b==a.j||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,1),b=Math.min(b,5E3),a.j=b,d(a),b=a.j,a.N.innerHTML=`\\( \\rightarrow V_{1}=${b}\\,\\text{km/h}=${b}/3.6=${(b/3.6).toFixed(1)}\\,\\text{m/s} \\)`,e(),f(a),g(a)),a.B.value=`${a.j}`)}
function k(a,b){a.g&&b==a.m||(a.g&&b==a.m||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,1),b=Math.min(b,500),a.m=b,d(a),a.R.innerHTML=`\\( p_{1}=${a.m}\\,\\text{kPa} \\)`,e(),f(a),g(a)),a.F.value=`${a.m}`)}function l(a,b){a.g&&b==a.h||(a.g&&b==a.h||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,1),b=Math.min(b,500),a.h=b,m(a,a.h+a.l),d(a),a.O.innerHTML=`\\( \\dot{m}_{1}=${a.h}\\,\\text{kg/s} \\)`,e(),n(a),f(a),g(a)),a.C.value=`${a.h}`)}
function p(a,b){a.g&&b==a.l||(a.g&&b==a.l||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,0),b=Math.min(b,100),a.l=b,m(a,a.h+a.l),a.P.innerHTML=`\\( ${a.l}\\,\\text{kg/s} \\)`,e(),n(a)),a.D.value=`${a.l}`)}function q(a,b){a.g&&b==a.o||(a.g&&b==a.o||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,1),b=Math.min(b,600),a.o=b,d(a),a.S.innerHTML=`\\( \\rightarrow p_{2}=${a.o}\\,\\text{kPa} \\)`,e(),f(a),g(a)),a.G.value=`${a.o}`)}
function r(a,b){a.g&&b==a.i||(a.g&&b==a.i||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,.01),b=Math.min(b,10),a.i=b,d(a),a.L.innerHTML=`\\( A_{\\text{exit}}=${a.i}\\,\\text{m}^{2} \\)`,e(),f(a),g(a)),a.A.value=`${a.i}`)}function d(a){var b=(a.u*1E3+a.j/3.6*a.h-(a.o-a.m)*1E3*a.i)/a.v;a.g&&b==a.I||a.g&&b==a.I||Number.isNaN(b)||!Number.isFinite(b)||(a.I=b,a.K.innerHTML=`$$ \\boxed{V_{2}=${a.I.toPrecision(6)}\\,\\text{m/s}}\\ . $$`,e())}
function m(a,b){a.g&&b==a.v||a.g&&b==a.v||Number.isNaN(b)||!Number.isFinite(b)||(a.v=b,d(a),n(a),f(a),g(a))}function n(a){a.T.innerHTML=`$$ \\dot{m}_{2}=${a.h}+${a.l}=${a.v}\\,\\text{kg/s} $$`;e()}function f(a){a.U.innerHTML=`$$ ${a.u}\\times10^{3} = ${a.v}\\times V_{2}-${a.h}\\times${(a.j/3.6).toFixed(1)}+\\left(${a.o}\\times10^{3}-${a.m}\\times10^{3}\\right)\\times${a.i} $$`;e()}
function g(a){a.J.innerHTML=`$$ V_{2}=\\frac{${a.u}\\times10^{3}+${a.h}\\times${(a.j/3.6).toFixed(1)}-\\left(${a.o}\\times10^{3}-${a.m}\\times10^{3}\\right)\\times${a.i}}{${a.v}} $$`;e()}
class t{constructor(){this.g=!1;this.H=document.getElementById("thrust");this.H.addEventListener("change",()=>c(this,parseInt(this.H.value,10)));this.H.step="1";this.H.min="1";this.H.max="500";this.B=document.getElementById("V1");this.B.addEventListener("change",()=>h(this,parseInt(this.B.value,10)));this.B.step="1";this.B.min="1";this.B.max="5000";this.F=document.getElementById("p1");this.F.addEventListener("change",()=>k(this,parseInt(this.F.value,10)));this.F.step="1";this.F.min="1";this.F.max=
"500";this.C=document.getElementById("ma");this.C.addEventListener("change",()=>l(this,parseInt(this.C.value,10)));this.C.step="1";this.C.min="1";this.C.max="500";this.D=document.getElementById("mf");this.D.addEventListener("change",()=>p(this,parseFloat(this.D.value)));this.D.step="0.1";this.D.min="0.0";this.D.max="100.0";this.G=document.getElementById("p2");this.G.addEventListener("change",()=>q(this,parseInt(this.G.value,10)));this.G.step="1";this.G.min="1";this.G.max="600";this.A=document.getElementById("A");
this.A.addEventListener("change",()=>r(this,parseFloat(this.A.value)));this.A.step="0.01";this.A.min="0.01";this.A.max="10";this.M=document.getElementById("given-thrust");this.P=document.getElementById("given-mf");this.N=document.getElementById("given-V1");this.R=document.getElementById("given-p1");this.O=document.getElementById("given-ma");this.S=document.getElementById("given-p2");this.L=document.getElementById("given-A");this.T=document.getElementById("mass-eqn");this.U=document.getElementById("thrust-eqn");
this.J=document.getElementById("V2-eqn");this.K=document.getElementById("V2-out");this.u=18;this.j=900;this.m=50;this.h=75;this.l=3;this.o=55;this.i=.2;this.I=this.v=0;c(this,this.u);h(this,this.j);k(this,this.m);l(this,this.h);p(this,this.l);q(this,this.o);r(this,this.i);this.g=!0}}function e(){typeof MathJax!="undefined"?MathJax.typesetPromise():console.log("MathJax not loaded yet!")}new t;
