function c(a){switch(a){case "air":return 1.404;case "argon":return 1.667;case "co2":return 1.3;case "freon12":return 1.139;case "helium":return 1.667;case "hydrogen":return 1.407;case "xenon":return 1.667}}function e(a){switch(a){case "air":return 28.96;case "argon":return 39.94;case "co2":return 44.01;case "freon12":return 120.9;case "helium":return 4.003;case "hydrogen":return 2.016;case "xenon":return 131.3}}
function h(a){switch(a){case "air":return"Air";case "argon":return"Argon (Ar)";case "co2":return"Carbon-dioxide (CO<sub>2</sub>)";case "freon12":return"Freon 12 (CCl<sub>2</sub>F<sub>2</sub>)";case "helium":return"Helium (He)";case "hydrogen":return"Hydrogen (H<sub>2</sub>)";case "xenon":return"Xeon (Xe)"}}
function k(a,b){if(!a.g||b!=a.u){if(!(a.g&&b==a.u||!"co2 air argon freon12 helium hydrogen xenon".split(" ").includes(b)||(a.u=b,b=c(a.u),a.g&&b==a.o||a.g&&b==a.o||Number.isNaN(b)||!Number.isFinite(b)||(a.o=b,b=a.o,l(a,b*a.j/(b-1)),a.S.innerText=`${a.o}`,a.Y.innerHTML=`\\( \\gamma=${a.o} \\)`,m(),n(a)),b=e(a.u),a.g&&b==a.C||a.g&&b==a.C||Number.isNaN(b)||!Number.isFinite(b)||(a.C=b,b=8314/a.C,a.g&&b==a.j||a.g&&b==a.j||Number.isNaN(b)||!Number.isFinite(b)||(a.j=b,b=a.o,l(a,b*a.j/(b-1)),p(a),r(a),n(a),
t(a)),a.aa.innerText=`${a.C}`,r(a)),b=h(a.u),a.g&&b==a.K)||a.g&&b==a.K)){a.K=b;b=a.K;var d=a.T;for(const f of d)f.innerHTML=b}a.J.value=`${a.u}`}}function u(a,b){a.g&&b==a.h||(a.g&&b==a.h||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,1),b=Math.min(b,1E3),a.h=b,v(a),w(a,a.B*a.h),a.W.innerHTML=`\\( V_{1} = ${a.h}\\,\\text{m/s} \\)`,m(),x(a),y(a),z(a)),a.G.value=`${a.h}`)}
function A(a,b){a.g&&b==a.i||(a.g&&b==a.i||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,-50),b=Math.min(b,1E3),a.i=b,v(a),p(a),b=a.i,a.U.innerHTML=`\\( T_{1} = ${b}^{\\circ}\\,\\text{C} = ${b+273}\\,\\text{K} \\)`,m(),x(a),y(a),t(a)),a.D.value=`${a.i}`)}function B(a,b){a.g&&b==a.v||(a.g&&b==a.v||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,1),b=Math.min(b,5E3),a.v=b,p(a),a.Z.innerHTML=`\\( p_{1} = ${a.v}\\,\\text{kPa} \\)`,m(),t(a)),a.I.value=`${a.v}`)}
function C(a,b){a.g&&b==a.m||(a.g&&b==a.m||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,1),b=Math.min(b,1E3),a.m=b,v(a),a.X.innerHTML=`\\( V_{e} = ${a.m}\\,\\text{m/s} \\)`,m(),x(a),y(a)),a.H.value=`${a.m}`)}function D(a,b){a.g&&b==a.l||(a.g&&b==a.l||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,-50),b=Math.min(b,1E3),a.l=b,v(a),b=a.l,a.V.innerHTML=`\\( T_{e} = ${b}^{\\circ}\\,\\text{C} = ${b+273}\\,\\text{K} \\)`,m(),x(a),y(a)),a.F.value=`${a.l}`)}
function v(a){var b=a.A;var d=a.m,f=a.h;b=b*(a.l+273)+d*d/2-b*(a.i+273)-f*f/2;a.g&&b==a.M||a.g&&b==a.M||Number.isNaN(b)||!Number.isFinite(b)||(a.M=b,a.ca.innerHTML=`$$ \\boxed{\\dot{q}/\\dot{m}=${E(a.M)}\\,\\text{J/kg}}\\ . $$`,m())}function p(a){var b=a.v*1E3/a.j/(a.i+273);a.g&&b==a.B||a.g&&b==a.B||Number.isNaN(b)||!Number.isFinite(b)||(a.B=b,w(a,a.B*a.h),t(a),z(a))}function l(a,b){a.g&&b==a.A||a.g&&b==a.A||Number.isNaN(b)||!Number.isFinite(b)||(a.A=b,v(a),n(a),x(a),y(a))}
function w(a,b){a.g&&b==a.L||a.g&&b==a.L||Number.isNaN(b)||!Number.isFinite(b)||(a.L=b,a.N.innerHTML=`$$ \\boxed{\\dot{m}/A=${E(a.L)}\\,\\text{kg/s-m}^{2}}\\ . $$`,m())}function r(a){a.O.innerHTML=`$$ R=\\frac{R_{u}}{\\hat{m}}=\\frac{8314}{${a.C}}=${E(a.j)}\\,\\text{J/kg-K}\\ . $$`;m()}function n(a){var b=a.o,d=a.A;a.P.innerHTML=`$$ c_{p}=\\frac{\\gamma\\,R}{\\gamma-1}=\\frac{${b}\\times ${E(a.j)}}{${b}-1}=${E(d)}\\,\\text{J/kg-K}\\ . $$`;m()}
function x(a){var b=a.A,d=a.i,f=a.h,g=a.l,q=a.m;d+=273;g+=273;a.R.innerHTML=`$$ ${E(b)}\\times${d}+\\frac{${f}^{2}}{2}+\\dot{q}/\\dot{m}=${E(b)}\\times${g}+\\frac{${q}^{2}}{2} $$`;m()}function y(a){var b=a.A,d=a.i,f=a.h,g=a.l,q=a.m;d+=273;g+=273;a.ba.innerHTML=`$$ \\dot{q}/\\dot{m}=${E(b)}\\times${g}+\\frac{${q}^{2}}{2}-${E(b)}\\times${d}-\\frac{${f}^{2}}{2} $$`;m()}
function t(a){var b=a.v,d=a.j,f=a.i,g=a.B;f+=273;a.da.innerHTML=`$$ \\rho_{1}=\\frac{p_{1}}{R\\,T_{1}}=\\frac{${b}\\times10^{3}}{${E(d)}\\times${f}}=${E(g)}\\,\\text{kg/m}^{3} $$`;m()}function z(a){var b=a.h;a.$.innerHTML=`$$ \\dot{m}/A=\\rho_{1}V_{1}=${E(a.B)}\\times${b} $$`;m()}
class F{constructor(){this.g=!1;this.J=document.getElementById("gases");this.J.addEventListener("change",()=>k(this,this.J.value));if(this.J.options.length!=7)throw Error("Number of options do not match with Gases type.");for(const a of this.J.options)if(!"co2 air argon freon12 helium hydrogen xenon".split(" ").includes(a.value))throw Error("'"+a.value+"' is not a valid option value for Gases.");this.G=document.getElementById("V1");this.G.addEventListener("change",()=>u(this,parseFloat(this.G.value)));
this.G.step="0.1";this.G.min="1";this.G.max="1000";this.D=document.getElementById("T1");this.D.addEventListener("change",()=>A(this,parseFloat(this.D.value)));this.D.step="0.1";this.D.min="-50";this.D.max="1000";this.I=document.getElementById("p1");this.I.addEventListener("change",()=>B(this,parseFloat(this.I.value)));this.I.step="0.1";this.I.min="1";this.I.max="5000";this.H=document.getElementById("Ve");this.H.addEventListener("change",()=>C(this,parseFloat(this.H.value)));this.H.step="0.1";this.H.min=
"1";this.H.max="1000";this.F=document.getElementById("Te");this.F.addEventListener("change",()=>D(this,parseFloat(this.F.value)));this.F.step="0.1";this.F.min="-50";this.F.max="1000";this.S=document.getElementById("gamma-out");this.T=document.getElementsByClassName("gas-name-out");this.Y=document.getElementById("given-gamma");this.W=document.getElementById("given-V1");this.U=document.getElementById("given-T1");this.Z=document.getElementById("given-p1");this.X=document.getElementById("given-Ve");this.V=
document.getElementById("given-Te");this.aa=document.getElementById("molar-mass-out");this.O=document.getElementById("R-out");this.P=document.getElementById("cp-out");this.R=document.getElementById("energy-eqn");this.ba=document.getElementById("q_m-eqn");this.ca=document.getElementById("q_m-out");this.da=document.getElementById("rho1-out");this.$=document.getElementById("m_A-eqn");this.N=document.getElementById("m_A-out");this.u="co2";this.h=120;this.i=200;this.v=700;this.m=240;this.l=450;this.o=
1.3;this.C=44;this.K="carbon-dioxide";this.j=189;this.A=819;this.M=226295;this.B=7.8;this.L=940;k(this,this.u);u(this,this.h);A(this,this.i);B(this,this.v);C(this,this.m);D(this,this.l);this.g=!0}}function m(){typeof MathJax!="undefined"?MathJax.typesetPromise():console.log("MathJax not loaded yet!")}function E(a){a=a.toPrecision(6).toLowerCase();a.includes("e+")?a=a.replace("e+","\\times 10^{")+"}":a.includes("e")&&(a=a.replace("e","\\times 10^{")+"}");return a}new F;
