function c(a,b){a.g&&b==a.h||(a.g&&b==a.h||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,1),b=Math.min(b,200),a.h=b,b=a.h,e(a,b+b/a.l),b=a.h,f(a,b+b/a.m),a.L.innerHTML=`\\( \\dot{m}_{1}=${a.h}\\,\\text{kg/s} \\)`,g(),a.M.innerHTML=`\\( \\dot{m}_{1}=${a.h}\\,\\text{kg/s}, \\)`,g(),h(a),k(a)),a.C.value=`${a.h}`)}
function l(a,b){a.g&&b==a.l||(a.g&&b==a.l||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,15),b=Math.min(b,200),a.l=b,b=a.h,e(a,b+b/a.l),a.J.innerHTML=`\\( \\dot{m}_{1}:\\dot{m}_{\\text{fuel}}=${a.l}:1 \\)`,g(),h(a)),a.A.value=`${a.l}`)}function m(a,b){a.g&&b==a.i||(a.g&&b==a.i||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,1),b=Math.min(b,5E3),a.i=b,n(a,a.o*a.i),a.H.innerHTML=`\\( V_{2}=${a.i}\\,\\text{m/s} \\)`,g(),p(a)),a.D.value=`${a.i}`)}
function q(a,b){a.g&&b==a.m||(a.g&&b==a.m||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,15),b=Math.min(b,200),a.m=b,b=a.h,f(a,b+b/a.m),a.K.innerHTML=`\\( \\dot{m}_{1}:\\dot{m}_{\\text{fuel}}=${a.m}:1, \\)`,g(),k(a)),a.B.value=`${a.m}`)}function r(a,b){a.g&&b==a.j||(a.g&&b==a.j||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,1),b=Math.min(b,5E3),a.j=b,t(a,a.u*a.j),a.I.innerHTML=`\\( V_{2}=${a.j}\\,\\text{m/s} \\)`,g(),u(a)),a.v.value=`${a.j}`)}
function e(a,b){a.g&&b==a.o||a.g&&b==a.o||Number.isNaN(b)||!Number.isFinite(b)||(a.o=b,n(a,a.o*a.i),h(a),p(a))}function f(a,b){a.g&&b==a.u||a.g&&b==a.u||Number.isNaN(b)||!Number.isFinite(b)||(a.u=b,t(a,a.u*a.j),k(a),u(a))}function n(a,b){a.g&&b==a.F||a.g&&b==a.F||Number.isNaN(b)||!Number.isFinite(b)||(a.F=b,a.S.innerHTML=`$$ \\boxed{\\text{Static thrust}=${a.F.toPrecision(6)}\\,\\text{N}}\\ . $$`,g())}
function t(a,b){a.g&&b==a.G||a.g&&b==a.G||Number.isNaN(b)||!Number.isFinite(b)||(a.G=b,a.T.innerHTML=`$$ \\boxed{\\text{Static thrust}=${a.G.toPrecision(6)}\\,\\text{N}}\\ . $$`,g())}function h(a){var b=a.h,d=a.l;a.N.innerHTML=`$$ \\dot{m}_{2}=\\dot{m}_{1}+\\dot{m}_{f1}=\\dot{m}_{1}+\\dot{m}_{1}/${d}=${b}+${b}/${d}=${a.o.toFixed(1)}\\,\\text{kg/s}. $$`;g()}function p(a){a.P.innerHTML=`$$ \\text{Thrust} = ${a.o.toFixed(1)}\\times${a.i} $$`;g()}
function k(a){var b=a.h,d=a.m;a.O.innerHTML=`$$ \\dot{m}_{2}=\\dot{m}_{1}+\\left(\\dot{m}_{f1}+\\dot{m}_{f2}\\right)=\\dot{m}_{1}+\\dot{m}_{1}/${d}=${b}+${b}/${d}=${a.u.toFixed(1)}\\,\\text{kg/s}. $$`;g()}function u(a){a.R.innerHTML=`$$ \\text{Thrust} = ${a.u.toFixed(1)}\\times${a.j} $$`;g()}
class v{constructor(){this.g=!1;this.C=document.getElementById("m1");this.C.addEventListener("change",()=>c(this,parseInt(this.C.value,10)));this.C.step="1";this.C.min="1";this.C.max="200";this.A=document.getElementById("af-ratio-1");this.A.addEventListener("change",()=>l(this,parseInt(this.A.value,10)));this.A.step="1";this.A.min="15";this.A.max="200";this.D=document.getElementById("V2-1");this.D.addEventListener("change",()=>m(this,parseInt(this.D.value,10)));this.D.step="1";this.D.min="1";this.D.max=
"5000";this.B=document.getElementById("af-ratio-2");this.B.addEventListener("change",()=>q(this,parseInt(this.B.value,10)));this.B.step="1";this.B.min="15";this.B.max="200";this.v=document.getElementById("V2-2");this.v.addEventListener("change",()=>r(this,parseInt(this.v.value,10)));this.v.step="1";this.v.min="1";this.v.max="5000";this.L=document.getElementById("given-m1-1");this.J=document.getElementById("given-af-ratio-1");this.H=document.getElementById("given-V2-1");this.M=document.getElementById("given-m1-2");
this.K=document.getElementById("given-af-ratio-2");this.I=document.getElementById("given-V2-2");this.N=document.getElementById("m2-eqn-1");this.P=document.getElementById("thrust-eqn-1");this.S=document.getElementById("thrust-out-1");this.O=document.getElementById("m2-eqn-2");this.R=document.getElementById("thrust-eqn-2");this.T=document.getElementById("thrust-out-2");this.h=50;this.l=90;this.i=600;this.m=50;this.j=730;this.G=this.F=this.u=this.o=0;c(this,this.h);l(this,this.l);m(this,this.i);q(this,
this.m);r(this,this.j);this.g=!0}}let w=!1;document.getElementById("MathJax-script")?.addEventListener("load",()=>{w=!0;console.log("MathJax loaded successfully!")});function g(){w?MathJax.typesetPromise():console.log("MathJax not loaded yet!")}new v;
