function d(a,b){a.g&&b==a.j||(a.g&&b==a.j||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,1),b=Math.min(b,1E3),a.j=b,g(a,a.j*1E3/287/(a.i+273)),k(a),a.T.innerText=`${a.j}`,l(a),m(a),n(a)),a.F.value=`${a.j}`)}function p(a,b){a.g&&b==a.i||(a.g&&b==a.i||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,-50),b=Math.min(b,1E3),a.i=b,g(a,a.j*1E3/287/(a.i+273)),k(a),a.P.innerText=`${a.i}`,l(a),m(a),n(a)),a.B.value=`${a.i}`)}
function q(a,b){a.g&&b==a.h||(a.g&&b==a.h||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,1),b=Math.min(b,1E3),a.h=b,k(a),r(a),t(a),u(a,-a.h*a.u/1005),a.R.innerText=`${a.h}`,m(a),v(a),w(a),n(a)),a.C.value=`${a.h}`)}function x(a,b){a.g&&b==a.l||(a.g&&b==a.l||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,.01),b=Math.min(b,10),a.l=b,k(a),t(a),a.O.innerText=`${a.l}`,m(a),w(a),n(a)),a.A.value=`${a.l}`)}
function y(a,b){a.g&&b==a.m||(a.g&&b==a.m||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,.01),b=Math.min(b,10),a.m=b,k(a),t(a),a.S.innerText=`${a.m}`,m(a),w(a),n(a)),a.D.value=`${a.m}`)}function k(a){var b=a.l;var c=a.o,e=a.h;b=a.m/(b/(2*c*1005*(a.i+273))+b/(2*c*e*e)-b/(2*a.j*1E3));if(!(a.g&&b==a.v||a.g&&b==a.v||Number.isNaN(b))&&Number.isFinite(b)){a.v=b;r(a);b=a.v;c=a.L;for(const f of c)f.innerHTML=`\\[ \\boxed{\\frac{dp}{dx}= ${z(b)}\\, \\text{Pa/m} }\\ . \\]`;A();v(a);B(a)}}
function r(a){var b=-a.v/a.h/a.o;if(!(a.g&&b==a.u||a.g&&b==a.u||Number.isNaN(b))&&Number.isFinite(b)){a.u=b;t(a);u(a,-a.h*a.u/1005);v(a);b=a.u;var c=a.J;for(const e of c)e.innerHTML=`\\[ \\boxed{\\frac{dV}{dx}= ${z(b)}\\,\\text{(m/s)/m}}\\ . \\]`;A();w(a);B(a)}}
function t(a){var b=a.o;b=-b/a.h*a.u-2*b/a.l*a.m;if(!(a.g&&b==a.G||a.g&&b==a.G||Number.isNaN(b))&&Number.isFinite(b)){a.G=b;b=a.G;var c=a.N;for(const e of c)e.innerHTML=`\\[ \\boxed{\\frac{d\\rho}{dx}= ${z(b)}\\,\\text{(kg/m}^{3}\\text{)/m}}\\ . \\]`;A();B(a)}}function g(a,b){a.g&&b==a.o||a.g&&b==a.o||Number.isNaN(b)||!Number.isFinite(b)||(a.o=b,k(a),r(a),t(a),l(a),m(a),v(a),w(a),n(a))}function u(a,b){a.g&&b==a.H||a.g&&b==a.H||Number.isNaN(b)||!Number.isFinite(b)||(a.H=b,B(a))}
function l(a){a.W.innerHTML=`\\[ \\rho=\\frac{p}{R\\,T}=\\frac{${a.j}\\times10^{3}}{${287}\\times${a.i+273}}= ${z(a.o)}\\, \\text{kg/m}^3\\ . \\]`;A()}function m(a){var b=a.l,c=a.o,e=a.i,f=a.h,h=a.j;a.K.innerHTML=`\\[ \\frac{dp}{dx}=\\frac{${a.m}}{\\left(\\frac{${b}}{2\\times${z(c)}\\times${1005}\\times${e}}+\\frac{${b}}{2\\times${z(c)}\\times${f}^{2}}-\\frac{${b}}{2\\times${h}\\times10^{3}}\\right)} \\]`;A()}
function v(a){var b=a.o,c=a.h,e=a.u;a.I.innerHTML=`\\[ \\frac{dV}{dx}=-\\frac{${z(a.v)}}{${c}\\times${z(b)}}= ${z(e)}\\, \\text{(m/s)/m} \\]`;A()}function w(a){var b=a.o,c=a.h,e=a.u,f=a.l,h=a.m;a.M.innerHTML=`\\[ \\frac{d\\rho}{dx}=\\frac{${z(b)}}{${c}}\\times${z(e)}-\\frac{2\\times${z(b)}}{${f}}\\times${h} \\]`;A()}
function n(a){var b=a.h,c=a.o,e=a.j,f=a.i,h=a.l,C=a.m;a=a.U;f+=273;c=z(c);h=z(-2/h*C);a.innerHTML=`\\[ \\left[\\begin{array}{cccc} 0 & 1/${b} & 1/${c} & 0\\\\ 1/${c} & ${b} & 0 & 0\\\\ 0 & ${b} & 0 & ${1005}\\\\ 1/\\left(${e}\\times10^{3}\\right) & 0 & -1/${c} & -1/${f} \\end{array}\\right]\\left[\\begin{array}{c} dp/dx\\\\ dV/dx\\\\ d\\rho/dx\\\\ dT/dx \\end{array}\\right]=\\left[\\begin{array}{c} ${h}\\\\ 0\\\\ 0\\\\ 0 \\end{array}\\right]\\ , \\] \\[ \\left[\\begin{array}{c} dp/dx\\\\ dV/dx\\\\ d\\rho/dx\\\\ dT/dx \\end{array}\\right]=\\left[\\begin{array}{cccc} 0 & 1/${b} & 1/${c} & 0\\\\ 1/${c} & ${b} & 0 & 0\\\\ 0 & ${b} & 0 & ${1005}\\\\ 1/\\left(${e}\\times10^{3}\\right) & 0 & -1/${c} & -1/${f} \\end{array}\\right]^{-1}\\left[\\begin{array}{c} ${h}\\\\ 0\\\\ 0\\\\ 0 \\end{array}\\right]\\ , \\]`;A()}
function B(a){var b=a.u,c=a.G,e=a.H;a.V.innerHTML=`\\[ \\left[\\begin{array}{c} dp/dx\\\\ dV/dx\\\\ d\\rho/dx\\\\ dT/dx \\end{array}\\right]=\\left[\\begin{array}{c} ${z(a.v)}\\\\ ${z(b)}\\\\ ${z(c)}\\\\ ${z(e)} \\end{array}\\right]\\ . \\]`;A()}
class D{constructor(){this.g=!1;this.F=document.getElementById("p");this.F.addEventListener("change",()=>d(this,parseFloat(this.F.value)));this.F.step="0.1";this.F.min="1";this.F.max="1000";this.B=document.getElementById("T");this.B.addEventListener("change",()=>p(this,parseFloat(this.B.value)));this.B.step="0.1";this.B.min="-50";this.B.max="1000";this.C=document.getElementById("V");this.C.addEventListener("change",()=>q(this,parseFloat(this.C.value)));this.C.step="0.1";this.C.min="1";this.C.max=
"1000";this.A=document.getElementById("D");this.A.addEventListener("change",()=>x(this,parseFloat(this.A.value)));this.A.step="0.01";this.A.min="0.01";this.A.max="10";this.D=document.getElementById("dD_dx");this.D.addEventListener("change",()=>y(this,parseFloat(this.D.value)));this.D.step="0.01";this.D.min="0.01";this.D.max="10";this.T=document.getElementById("given-p");this.P=document.getElementById("given-T");this.R=document.getElementById("given-V");this.O=document.getElementById("given-D");this.S=
document.getElementById("given-dD_dx");this.W=document.getElementById("rho-out");this.K=document.getElementById("dp_dx-eqn");this.L=document.getElementsByClassName("dp_dx-out");this.I=document.getElementById("dV_dx-eqn");this.J=document.getElementsByClassName("dV_dx-out");this.M=document.getElementById("drho_dx-eqn");this.N=document.getElementsByClassName("drho_dx-out");this.U=document.getElementById("matrix-form-eqn");this.V=document.getElementById("matrix-form-out");this.j=150;this.i=35;this.h=
250;this.l=.2;this.m=.1;this.o=1.69;this.v=214314;this.u=-505.2;this.G=1.732;this.H=125.7;d(this,this.j);p(this,this.i);q(this,this.h);x(this,this.l);y(this,this.m);this.g=!0}}function A(){typeof MathJax!="undefined"&&MathJax.typesetPromise()}function z(a){a=a.toPrecision(6).toLowerCase();a.includes("e+")?a=a.replace("e+","\\times 10^{")+"}":a.includes("e")&&(a=a.replace("e","\\times 10^{")+"}");return a}new D;
