function c(a,b){a.g&&b==a.h||(a.g&&b==a.h||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,0),a.h=b,d(a),e(a,a.h/a.o),f(a,a.h/a.u),a.H.innerHTML=`\\( m=${a.h}\\,\\text{kg} \\)`,g(),h(a),k(a)),a.B.value=`${a.h}`)}function l(a,b){a.g&&b==a.i||(a.g&&b==a.i||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,-10),b=Math.min(b,1E3),a.i=b,d(a),m(a),n(a,a.l*1E3/287/(a.i+273)),p(a),q(a)),a.A.value=`${a.i}`)}
function r(a,b){a.g&&b==a.l||(a.g&&b==a.l||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,1),a.l=b,d(a),m(a),n(a,a.l*1E3/287/(a.i+273)),p(a),q(a)),a.C.value=`${a.l}`)}function t(a,b){a.g&&b==a.j||(a.g&&b==a.j||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,-10),b=Math.min(b,1500),a.j=b,d(a),m(a),u(a,a.m*1E3/287/(a.j+273)),p(a),v(a)),a.v.value=`${a.j}`)}
function m(a){var b=a.l*Math.pow((a.j+273)/(a.i+273),1.4/(1.4-1));a.g&&b==a.m||a.g&&b==a.m||Number.isNaN(b)||!Number.isFinite(b)||(a.m=b,u(a,a.m*1E3/287/(a.j+273)),a.J.innerHTML=`$$ \\boxed{p_{2}=${a.m.toPrecision(6)}\\,\\text{kPa}}\\ . $$`,g(),v(a))}
function d(a){var b=a.i,w=a.j;a.G.innerHTML=`\\( m=${a.h}\\,\\text{kg} \\), \\( T_{1}=${b}^{\\circ}\\text{C}=${b+273}\\,\\text{K} \\), \\( p_{1}=${a.l}\\,\\text{kPa} \\), isentropic process, \\( T_{2}=${w}^{\\circ}\\text{C}=${w+273}\\,\\text{K} \\).`;g()}function n(a,b){a.g&&b==a.o||a.g&&b==a.o||Number.isNaN(b)||!Number.isFinite(b)||(a.o=b,e(a,a.h/a.o),a.L.innerHTML=`$$ \\boxed{\\rho_{1}=${a.o.toPrecision(6)}\\,\\text{kg/m}^{3}}\\ . $$`,g(),h(a))}
function u(a,b){a.g&&b==a.u||a.g&&b==a.u||Number.isNaN(b)||!Number.isFinite(b)||(a.u=b,f(a,a.h/a.u),a.N.innerHTML=`$$ \\boxed{\\rho_{2}=${a.u.toPrecision(6)}\\,\\text{kg/m}^{3}}\\ . $$`,g(),k(a))}function e(a,b){a.g&&b==a.D||a.g&&b==a.D||Number.isNaN(b)||!Number.isFinite(b)||(a.D=b,h(a))}function f(a,b){a.g&&b==a.F||a.g&&b==a.F||Number.isNaN(b)||!Number.isFinite(b)||(a.F=b,k(a))}
function p(a){a.I.innerHTML=`$$ p_{2}=${a.l}\\times10^{3}\\times\\left(\\frac{${a.j+273}}{${a.i+273}}\\right)^{1.4/\\left(1.4-1\\right)} $$`;g()}function q(a){a.K.innerHTML=`$$ \\rho_{1}=\\frac{p_{1}}{R\\,T_{1}}=\\frac{${a.l.toPrecision(6)}\\times10^{3}}{287\\times ${a.i+273}} $$`;g()}function v(a){a.M.innerHTML=`$$ \\rho_{2}=\\frac{p_{2}}{R\\,T_{2}}=\\frac{${a.m.toPrecision(6)}\\times10^{3}}{287\\times ${a.j+273}} $$`;g()}
function h(a){a.O.innerHTML=`$$ \\boxed{v_{1}=\\frac{m}{\\rho_{1}}=\\frac{${a.h}}{${a.o.toPrecision(6)}}=${a.D.toPrecision(6)}\\,\\text{m}^{3}} $$`;g()}function k(a){a.P.innerHTML=`$$ \\boxed{v_{2}=\\frac{m}{\\rho_{2}}=\\frac{${a.h}}{${a.u.toPrecision(6)}}=${a.F.toPrecision(6)}\\,\\text{m}^{3}} $$`;g()}
class x{constructor(){this.g=!1;this.B=document.getElementById("m");this.B.addEventListener("change",()=>c(this,parseInt(this.B.value,10)));this.B.step="1";this.B.min="0";this.A=document.getElementById("T1");this.A.addEventListener("change",()=>l(this,parseInt(this.A.value,10)));this.A.step="1";this.A.min="-10";this.A.max="1000";this.C=document.getElementById("p1");this.C.addEventListener("change",()=>r(this,parseInt(this.C.value,10)));this.C.step="1";this.C.min="1";this.v=document.getElementById("T2");
this.v.addEventListener("change",()=>t(this,parseInt(this.v.value,10)));this.v.step="1";this.v.min="-10";this.v.max="1500";this.G=document.getElementById("given");this.I=document.getElementById("p2-eqn-out");this.J=document.getElementById("p2-out");this.K=document.getElementById("rho1-eqn-out");this.L=document.getElementById("rho1-out");this.M=document.getElementById("rho2-eqn-out");this.N=document.getElementById("rho2-out");this.H=document.getElementById("m-out");this.O=document.getElementById("vol1-out");
this.P=document.getElementById("vol2-out");this.h=2;this.i=30;this.l=100;this.j=850;this.F=this.D=this.u=this.o=this.m=0;c(this,this.h);l(this,this.i);r(this,this.l);t(this,this.j);this.g=!0}}let y=!1;document.getElementById("MathJax-script")?.addEventListener("load",()=>{y=!0;console.log("MathJax loaded successfully!")});function g(){y?MathJax.typesetPromise():console.log("MathJax not loaded yet!")}new x;
