function c(a,b){a.g&&b==a.j||(a.g&&b==a.j||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,.1),b=Math.min(b,5E3),a.j=b,d(a),e(a),a.N.innerHTML=`\\( \\dot{m}=${a.j}\\,\\text{kg/s} \\)`,f(),g(a),h(a)),a.C.value=`${a.j}`)}function k(a,b){a.g&&b==a.o||(a.g&&b==a.o||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,.01),b=Math.min(b,100),a.o=b,e(a),a.J.innerHTML=`\\( A_{1}=${a.o}\\,\\text{m}^{2} \\)`,f(),h(a)),a.G.value=`${a.o}`)}
function l(a,b){a.g&&b==a.u||(a.g&&b==a.u||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,.01),b=Math.min(b,100),a.u=b,d(a),a.K.innerHTML=`\\( A_{e}=${a.u}\\,\\text{m}^{2} \\)`,f(),g(a)),a.v.value=`${a.u}`)}function m(a,b){a.g&&b==a.l||(a.g&&b==a.l||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,.1),b=Math.min(b,5E4),a.l=b,d(a),e(a),a.O.innerHTML=`\\( p_{1}=${a.l}\\,\\text{kPa} \\)`,f(),g(a),h(a)),a.D.value=`${a.l}`)}
function n(a,b){a.g&&b==a.h||(a.g&&b==a.h||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,.1),b=Math.min(b,5E3),a.h=b,d(a),e(a),a.L.innerHTML=`\\( V_{1}=${a.h}\\,\\text{m/s} \\)`,f(),g(a),h(a)),a.A.value=`${a.h}`)}function p(a,b){a.g&&b==a.m||(a.g&&b==a.m||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,.1),b=Math.min(b,5E3),a.m=b,d(a),e(a),a.P.innerHTML=`\\( p_{e}=${a.m}\\,\\text{kPa} \\)`,f(),g(a),h(a)),a.F.value=`${a.m}`)}
function q(a,b){a.g&&b==a.i||(a.g&&b==a.i||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,.1),b=Math.min(b,5E4),a.i=b,d(a),e(a),a.M.innerHTML=`\\( V_{e}=${a.i}\\,\\text{m/s} \\)`,f(),g(a),h(a)),a.B.value=`${a.i}`)}function d(a){var b=(a.j*(a.i-a.h)+(a.m*1E3-a.l*1E3)*a.u)/1E3;a.g&&b==a.H||a.g&&b==a.H||Number.isNaN(b)||!Number.isFinite(b)||(a.H=b,a.S.innerHTML=`$$ \\boxed{\\text{Thrust force on nozzle}=${r(a.H)}\\,\\text{kN}}\\ $$`,f())}
function e(a){var b=(a.j*(a.i-a.h)+(a.m*1E3-a.l*1E3)*a.o)/1E3;a.g&&b==a.I||a.g&&b==a.I||Number.isNaN(b)||!Number.isFinite(b)||(a.I=b,a.U.innerHTML=`$$ \\boxed{\\text{Thrust force on nozzle}=${r(a.I)}\\,\\text{kN}}\\ . $$`,f())}function g(a){a.R.innerHTML=`$$ \\text{Thrust force on nozzle} = ${a.j}\\times\\left(${a.i}-${a.h}\\right)+\\left(${a.m}\\times10^{3}-${a.l}\\times10^{3}\\right)\\times${a.u}\\ . $$`;f()}
function h(a){a.T.innerHTML=`$$ \\text{Thrust force on nozzle}=${a.j}\\times\\left(${a.i}-${a.h}\\right)+\\left(${a.m}\\times10^{3}-${a.l}\\times10^{3}\\right)\\times${a.o}\\ . $$`;f()}
class t{constructor(){this.g=!1;this.C=document.getElementById("m");this.C.addEventListener("change",()=>c(this,parseFloat(this.C.value)));this.C.step="0.1";this.C.min="0.1";this.C.max="5000";this.G=document.getElementById("A1");this.G.addEventListener("change",()=>k(this,parseFloat(this.G.value)));this.G.step="0.01";this.G.min="0.01";this.G.max="100";this.v=document.getElementById("Ae");this.v.addEventListener("change",()=>l(this,parseFloat(this.v.value)));this.v.step="0.01";this.v.min="0.01";this.v.max=
"100";this.D=document.getElementById("p1");this.D.addEventListener("change",()=>m(this,parseFloat(this.D.value)));this.D.step="0.1";this.D.min="0.1";this.D.max="50000";this.A=document.getElementById("V1");this.A.addEventListener("change",()=>n(this,parseFloat(this.A.value)));this.A.step="0.1";this.A.min="0.1";this.A.max="5000";this.F=document.getElementById("pe");this.F.addEventListener("change",()=>p(this,parseFloat(this.F.value)));this.F.step="0.1";this.F.min="0.1";this.F.max="5000";this.B=document.getElementById("Ve");
this.B.addEventListener("change",()=>q(this,parseFloat(this.B.value)));this.B.step="0.1";this.B.min="0.1";this.B.max="50000";this.N=document.getElementById("given-m");this.J=document.getElementById("given-A1");this.O=document.getElementById("given-p1");this.L=document.getElementById("given-V1");this.K=document.getElementById("given-Ae");this.P=document.getElementById("given-pe");this.M=document.getElementById("given-Ve");this.R=document.getElementById("thrust1-eqn");this.S=document.getElementById("thrust1-out");
this.T=document.getElementById("thrust2-eqn");this.U=document.getElementById("thrust2-out");this.j=200;this.o=.7;this.u=2.4;this.l=1600;this.h=150;this.m=80;this.i=2300;this.H=-3218;this.I=-634;c(this,this.j);k(this,this.o);l(this,this.u);m(this,this.l);n(this,this.h);p(this,this.m);q(this,this.i);this.g=!0}}function f(){typeof MathJax!="undefined"&&MathJax.typesetPromise()}
function r(a){a=a.toPrecision(6).toLowerCase();a.includes("e+")?a=a.replace("e+","\\times 10^{")+"}":a.includes("e")&&(a=a.replace("e","\\times 10^{")+"}");return a}new t;
