function c(a,b){a.g&&b==a.i||(a.g&&b==a.i||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,1),b=Math.min(b,1E3),a.i=b,e(a),g(a),h(a,a.i*a.F),a.T.innerText=`${a.i}`,k(a),l(a)),a.B.value=`${a.i}`)}
function m(a,b){a.g&&b==a.h||(a.g&&b==a.h||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,-50),b=Math.min(b,1E3),a.h=b,b=a.h+273,a.g&&b==a.G||a.g&&b==a.G||Number.isNaN(b)||!Number.isFinite(b)||(a.G=b,a.U.innerText=`${a.G}`),n(a,a.j*1E3/287/(a.h+273)),p(a,1/(a.h+273)*a.u),a.S.innerText=`${a.h}`,r(a),t(a)),a.A.value=`${a.h}`)}
function u(a,b){a.g&&b==a.j||(a.g&&b==a.j||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,1),b=Math.min(b,1E3),a.j=b,n(a,a.j*1E3/287/(a.h+273)),v(a),a.W.innerText=`${a.j}`,r(a),w(a)),a.C.value=`${a.j}`)}function x(a,b){a.g&&b==a.l||(a.g&&b==a.l||!["decreasing","increasing"].includes(b)||(a.l=b,e(a),y(a),k(a),l(a)),a.J.value=`${a.l}`)}
function z(a,b){a.g&&b==a.m||(a.g&&b==a.m||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,0),b=Math.min(b,100),a.m=b,e(a),y(a),k(a),l(a)),a.D.value=`${a.m}`)}function e(a){a:{var b=a.m;var d=a.i;switch(a.l){case "increasing":b=b/100*d;break a;case "decreasing":b=-b/100*d;break a}b=void 0}a.g&&b==a.F||a.g&&b==a.F||Number.isNaN(b)||!Number.isFinite(b)||(a.F=b,g(a),h(a,a.i*a.F))}
function g(a){var b=-a.o*a.i*a.F;a.g&&b==a.v||a.g&&b==a.v||Number.isNaN(b)||!Number.isFinite(b)||(a.v=b,v(a),a.L.innerHTML=`\\[ \\boxed{\\frac{dp}{dx}= ${A(a.v,6)}\\,\\text{Pa/m}}\\ . \\]`,B(),w(a))}function v(a){var b=a.o/(a.j*1E3)*a.v;a.g&&b==a.H||a.g&&b==a.H||Number.isNaN(b)||!Number.isFinite(b)||(a.H=b,a.O.innerHTML=`\\[ \\boxed{\\frac{d\\rho}{dx}=${A(a.H,6)}\\,\\text{(kg/m}^{3}\\text{)/m}}\\ . \\]`,B())}
function n(a,b){a.g&&b==a.o||a.g&&b==a.o||Number.isNaN(b)||!Number.isFinite(b)||(a.o=b,g(a),v(a),r(a),k(a),w(a))}function h(a,b){a.g&&b==a.u||a.g&&b==a.u||Number.isNaN(b)||!Number.isFinite(b)||(a.u=b,p(a,1/(a.h+273)*a.u),l(a),t(a))}function p(a,b){a.g&&b==a.I||a.g&&b==a.I||Number.isNaN(b)||!Number.isFinite(b)||(a.I=b,a.R.innerHTML=`\\[ \\boxed{\\frac{ds}{dx}=${A(a.I,6)}\\,\\text{(J/kg-K)/m}}\\ . \\]`,B())}function y(a){a.V.innerText=`${a.l=="decreasing"?"-":"+"}${A(a.m*.01,2)}`}
function r(a){a.X.innerHTML=`\\[ \\rho=\\frac{p}{R\\,T}=\\frac{${a.j}\\times10^{3}}{287\\times${a.h+273}}= ${A(a.o,6)}\\,\\text{kg/m}^{3} \\]`;B()}function k(a){var b=a.o,d=a.i,q=a.K;const f=a.l=="decreasing"?"":"-";a=A(a.m*.01,2);q.innerHTML=`\\[ \\frac{dp}{dx}=${f}${a}\\rho\\,V^{2}=${f}${a}\\times${A(b,6)}\\times${d}^{2} \\]`;B()}
function l(a){var b=a.i,d=a.u,q=a.M;const f=a.l=="decreasing"?"-":"";a=`${A(a.m*.01,2)}`;q.innerHTML=`\\[ \\frac{dq}{dx}=V\\,\\left(${f}${a}\\,V\\right)=${f}${a}\\times${b}^{2}=${A(d,6)}\\,\\text{(J/kg)/m} \\]`;B()}function t(a){a.P.innerHTML=`\\[ \\frac{ds}{dx}=\\frac{1}{T}\\,\\frac{dq}{dx}=\\frac{1}{${a.h+273}}\\times\\left(${A(a.u,6)}\\right) \\]`;B()}function w(a){var b=a.j,d=a.v;a.N.innerHTML=`\\[ \\frac{d\\rho}{dx}=\\frac{${A(a.o,6)}}{${b}\\times10^{3}}\\times${A(d,6)} \\]`;B()}
class C{constructor(){this.g=!1;this.B=document.getElementById("V");this.B.addEventListener("change",()=>c(this,parseFloat(this.B.value)));this.B.step="1";this.B.min="1";this.B.max="1000";this.A=document.getElementById("T");this.A.addEventListener("change",()=>m(this,parseFloat(this.A.value)));this.A.step="1";this.A.min="-50";this.A.max="1000";this.C=document.getElementById("p");this.C.addEventListener("change",()=>u(this,parseFloat(this.C.value)));this.C.step="1";this.C.min="1";this.C.max="1000";
this.J=document.getElementById("change-dir");this.J.addEventListener("change",()=>x(this,this.J.value));this.D=document.getElementById("rate-percent");this.D.addEventListener("change",()=>z(this,parseFloat(this.D.value)));this.D.step="1";this.D.min="0";this.D.max="100";this.T=document.getElementById("given-V");this.S=document.getElementById("given-T");this.U=document.getElementById("given-TK");this.W=document.getElementById("given-p");this.V=document.getElementById("given-dV_dx");this.X=document.getElementById("rho-out");
this.K=document.getElementById("dp_dx-eqn");this.L=document.getElementById("dp_dx-out");this.M=document.getElementById("dq_dx-out");this.P=document.getElementById("ds_dx-eqn");this.R=document.getElementById("ds_dx-out");this.N=document.getElementById("drho_dx-eqn");this.O=document.getElementById("drho_dx-out");this.i=200;this.h=25;this.j=120;this.l="decreasing";this.m=30;this.F=-60;this.G=298;this.o=1.4;this.v=16836.9;this.u=-12E3;this.I=-40.3;this.H=.2;c(this,this.i);m(this,this.h);u(this,this.j);
x(this,this.l);z(this,this.m);this.g=!0}}function B(){typeof MathJax!="undefined"&&MathJax.typesetPromise()}function A(a,b){a=a.toPrecision(Math.max(1,Math.min(21,Math.floor(b)))).toLowerCase();a.includes("e+")?a=a.replace("e+","\\times 10^{")+"}":a.includes("e")&&(a=a.replace("e","\\times 10^{")+"}");return a}new C;
