function g(a){switch(a){case "air":return 1.404;case "argon":return 1.667;case "carbon dioxide":return 1.3;case "freon-12":return 1.139;case "helium":return 1.667;case "hydrogen":return 1.407;case "methane":return 1.32;case "xenon":return 1.667}}
function h(a){switch(a){case "air":return"Air";case "argon":return"Argon (Ar)";case "carbon dioxide":return"Carbon dioxide (CO<sub>2</sub>)";case "freon-12":return"Freon 12 (CCl<sub>2</sub>F<sub>2</sub>)";case "helium":return"Helium (He)";case "hydrogen":return"Hydrogen (H<sub>2</sub>)";case "methane":return"Methane (CH<sub>4</sub>)";case "xenon":return"Xenon (Xe)"}}const k=[],m=[],n=[],p=[];let q=null;
function r(a,b){if(!a.g||b!=a.o){if((!a.g||b!=a.o)&&"air;argon;carbon dioxide;freon-12;helium;hydrogen;methane;xenon".split(";").includes(b)){a.o=b;b=g(a.o);if(!(a.g&&b==a.l||a.g&&b==a.l||Number.isNaN(b))&&Number.isFinite(b)){a.l=b;b=a.l;var d=a.I;for(var c of d)c.innerText=`${b}`;t(a);u(a);v(a)}c=h(a.o);if(!a.g||c!=a.C)if(!a.g||c!=a.C){a.C=c;c=a.C;b=a.J;for(const l of b)l.innerHTML=c}}a.B.value=`${a.o}`}}
function w(a,b){if(!a.g||b!=a.m){if(!(a.g&&b==a.m||Number.isNaN(b))&&Number.isFinite(b)){b=Math.max(b,.1);b=Math.min(b,10);a.m=b;b=a.m*.01;if(!(a.g&&b==a.h||a.g&&b==a.h||Number.isNaN(b))&&Number.isFinite(b)){a.h=b;b=a.h;var d=a.F;for(var c of d)c.innerText=`${x(b,2)}`;t(a);u(a);b=a.h;c=a.H;y([c]);b=x(-b,3);c.innerHTML=`\\begin{equation} \\boxed{\\frac{d\\rho}{\\rho}=${b}\\,M^{2}}\\ .\\label{eq:drho_rho} \\end{equation}`;z();v(a)}a.K.innerText=`${a.m}`}a.u.value=`${a.m}`}}
function A(a,b){if(!a.g||b!=a.j){if(!(a.g&&b==a.j||Number.isNaN(b))&&Number.isFinite(b)){b=Math.max(b,.1);b=Math.min(b,5);a.g&&(b=Math.min(b,a.i-.1));a.j=b;b=a.j;var d=a.M;for(const c of d)c.innerText=`${b}`;v(a)}a.A.value=`${a.j}`}}function B(a,b){if(!a.g||b!=a.i){if(!(a.g&&b==a.i||Number.isNaN(b))&&Number.isFinite(b)){b=Math.max(b,.1);b=Math.min(b,5);a.g&&(b=Math.max(b,a.j+.1));a.i=b;b=a.i;var d=a.L;for(const c of d)c.innerText=`${b}`;v(a)}a.v.value=`${a.i}`}}
function t(a){var b=a.l,d=a.h;a=a.G;y([a]);b=x(-b*d,3);a.innerHTML=`\\begin{equation} \\boxed{\\frac{dp}{p}=${b}\\,M^{2}}\\ .\\label{eq:dp_p} \\end{equation}`;z()}function u(a){var b=a.l,d=a.h;a=a.D;y([a]);b=x(-(b-1)*d,3);a.innerHTML=`\\begin{equation} \\boxed{\\frac{dT}{T}=${b}\\,M^{2}}\\ .\\label{eq:dT_T} \\end{equation}`;z()}
function v(a){var b=a.l,d=a.h,c=a.j,l=a.N;a=(a.i-c)/499;for(let e=0;e<500;e++){const f=c+a*e;k[e]=Math.round(f*100)/100;m[e]=-b*f*f*d*100;n[e]=-(b-1)*f*f*d*100;p[e]=-f*f*d*100}b={plugins:{legend:!0},scales:{x:{beginAtZero:!1,title:{text:"Mach",display:!0,font:{size:16}}},y:{beginAtZero:!0,title:{text:"% change",display:!0,font:{size:16}}}}};q==null&&(q=new Chart(l,{type:"line",data:{labels:k,datasets:[{label:"dp/p",data:m,borderWidth:4,pointStyle:!1,cubicInterpolationMode:"monotone"},{label:"dT/T",
data:n,borderWidth:4,pointStyle:!1,cubicInterpolationMode:"monotone"},{label:"d\u03c1/\u03c1",data:p,borderWidth:4,pointStyle:!1,cubicInterpolationMode:"monotone"}]},options:b}));q.update()}
class C{constructor(){this.g=!1;this.B=document.getElementById("select-gas");this.B.addEventListener("change",()=>r(this,this.B.value));if(this.B.options.length!=8)throw Error("Number of options do not match with Gases type.");for(const a of this.B.options)if(!"air;argon;carbon dioxide;freon-12;helium;hydrogen;methane;xenon".split(";").includes(a.value))throw Error("'"+a.value+"' is not a valid option value for Gases.");this.u=document.getElementById("percent-dV_V");this.u.addEventListener("change",
()=>w(this,parseFloat(this.u.value)));this.u.step="0.1";this.u.min="0.1";this.u.max="10.0";this.A=document.getElementById("min-Mach");this.A.addEventListener("change",()=>A(this,parseFloat(this.A.value)));this.A.step="0.1";this.A.min="0.1";this.A.max="5.0";this.v=document.getElementById("max-Mach");this.v.addEventListener("change",()=>B(this,parseFloat(this.v.value)));this.v.step="0.1";this.v.min="0.1";this.v.max="5.0";this.M=document.getElementsByClassName("given-minMach");this.L=document.getElementsByClassName("given-maxMach");
this.J=document.getElementsByClassName("gas-name");this.K=document.getElementById("given-dV_V");this.F=document.getElementsByClassName("dV_V-out");this.I=document.getElementsByClassName("gamma-out");this.G=document.getElementById("dp_p-out");this.D=document.getElementById("dT_T-out");this.H=document.getElementById("drho_rho-out");this.N=document.getElementById("plot-percent-change");this.o="air";this.m=1;this.j=.2;this.i=2;this.l=1.4;this.C="air";this.h=.01;r(this,this.o);w(this,this.m);A(this,this.j);
B(this,this.i);this.g=!0}}function z(){typeof MathJax!="undefined"&&MathJax.typesetPromise?MathJax.typesetPromise():console.log("MathJax not loaded yet!")}function y(a){typeof MathJax!="undefined"&&MathJax.typesetPromise?(MathJax.typesetClear(a),MathJax.texReset()):console.log("MathJax not loaded yet!")}
function x(a,b){a=a.toPrecision(Math.max(1,Math.min(21,Math.floor(b)))).toLowerCase();a.includes("e+")?a=a.replace("e+","\\times 10^{")+"}":a.includes("e")&&(a=a.replace("e","\\times 10^{")+"}");return a}new C;
