function c(a,b){a.g&&b==a.h||(a.g&&b==a.h||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,.1),b=Math.min(b,100),a.h=b,e(a),f(a),a.H.innerHTML=`\\( D_{e}=\u2300${g(a.h*.01,3)}\\,\\text{m} \\)`,h(),k(a),q(a)),a.C.value=`${a.h}`)}function r(a,b){a.g&&b==a.o||(a.g&&b==a.o||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,1),b=Math.min(b,5E3),a.o=b,e(a),f(a),a.M.innerHTML=`\\( p_{e}=${a.o}\\,\\text{kPa} \\)`,h(),k(a),q(a)),a.B.value=`${a.o}`)}
function t(a,b){a.g&&b==a.i||(a.g&&b==a.i||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,.1),b=Math.min(b,5E3),a.i=b,e(a),f(a),a.I.innerHTML=`\\( V_{e}=${a.i}\\,\\text{m/s} \\)`,h(),k(a),q(a)),a.D.value=`${a.i}`)}function u(a,b){a.g&&b==a.j||(a.g&&b==a.j||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,.1),b=Math.min(b,5E3),a.j=b,e(a),f(a),a.J.innerHTML=`\\( \\dot{m}_{e}=${a.j}\\,\\text{kg/s} \\)`,h(),k(a),q(a)),a.u.value=`${a.j}`)}
function v(a,b){a.g&&b==a.l||(a.g&&b==a.l||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,.1),b=Math.min(b,5E3),a.l=b,e(a),a.K.innerHTML=`\\( p_{\\text{amb}} = ${a.l}\\,\\text{kPa} \\)`,h(),a.N.innerHTML=`\\( p_{\\text{amb}} = ${a.l}\\,\\text{kPa} \\)`,h(),k(a),w(a)),a.v.value=`${a.l}`)}
function x(a,b){a.g&&b==a.m||(a.g&&b==a.m||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,.1),b=Math.min(b,5E3),a.m=b,f(a),a.L.innerHTML=`\\( p_{\\text{amb}} = ${a.m}\\,\\text{kPa} \\)`,h(),a.O.innerHTML=`\\( p_{\\text{amb}} = ${a.m}\\,\\text{kPa} \\)`,h(),q(a),y(a)),a.A.value=`${a.m}`)}function e(a){var b=a.j;var l=a.i,m=a.o,n=a.l,d=a.h;const p=Math.PI/4;d*=.01;b=b*l+(m-n)*1E3*p*d*d;a.g&&b==a.F||a.g&&b==a.F||Number.isNaN(b)||!Number.isFinite(b)||(a.F=b,w(a))}
function f(a){var b=a.j;var l=a.i,m=a.o,n=a.m,d=a.h;const p=Math.PI/4;d*=.01;b=b*l+(m-n)*1E3*p*d*d;a.g&&b==a.G||a.g&&b==a.G||Number.isNaN(b)||!Number.isFinite(b)||(a.G=b,y(a))}function k(a){a.P.innerHTML=`$$ \\text{Thrust} = ${a.j}\\times${a.i}-0+\\left(${a.o}\\times10^{3}-${a.l}\\times10^{3}\\right)\\times\\frac{\\pi}{4}\\times${g(a.h/100,3)}^{2} $$`;h()}
function w(a){a.R.innerHTML=`$$ \\text{when }\\ p_{\\text{amb}}=${a.l}\\,\\text{kPa}\\quad\\implies\\quad\\boxed{\\text{Thrust}=${g(a.F,6)}\\,\\text{N}}\\ . $$`;h()}function q(a){a.S.innerHTML=`$$ \\text{Thrust} = ${a.j}\\times${a.i}-0+\\left(${a.o}\\times10^{3}-${a.m}\\times10^{3}\\right)\\times\\frac{\\pi}{4}\\times${g(a.h/100,3)}^{2} $$`;h()}
function y(a){a.T.innerHTML=`$$ \\text{when }\\ p_{\\text{amb}} = ${a.m}\\,\\text{kPa}\\quad\\implies\\quad\\boxed{\\text{Thrust}=${g(a.G,6)}\\,\\text{N}}\\ . $$`;h()}
class z{constructor(){this.g=!1;this.C=document.getElementById("De");this.C.addEventListener("change",()=>c(this,parseFloat(this.C.value)));this.C.step="0.1";this.C.min="0.1";this.C.max="100";this.B=document.getElementById("pe");this.B.addEventListener("change",()=>r(this,parseFloat(this.B.value)));this.B.step="0.1";this.B.min="1";this.B.max="5000";this.D=document.getElementById("Ve");this.D.addEventListener("change",()=>t(this,parseFloat(this.D.value)));this.D.step="0.1";this.D.min="0.1";this.D.max=
"5000";this.u=document.getElementById("me");this.u.addEventListener("change",()=>u(this,parseFloat(this.u.value)));this.u.step="0.1";this.u.min="0.1";this.u.max="5000";this.v=document.getElementById("pa1");this.v.addEventListener("change",()=>v(this,parseFloat(this.v.value)));this.v.step="0.1";this.v.min="0.1";this.v.max="5000";this.A=document.getElementById("pa2");this.A.addEventListener("change",()=>x(this,parseFloat(this.A.value)));this.A.step="0.1";this.A.min="0.1";this.A.max="5000";this.J=document.getElementById("given-me");
this.I=document.getElementById("given-Ve");this.M=document.getElementById("given-pe");this.H=document.getElementById("given-De");this.K=document.getElementById("given-pa1");this.L=document.getElementById("given-pa2");this.N=document.getElementById("heading-pa1");this.P=document.getElementById("thrust1-eqn");this.R=document.getElementById("thrust1-out");this.O=document.getElementById("heading-pa2");this.S=document.getElementById("thrust2-eqn");this.T=document.getElementById("thrust2-out");this.h=30;
this.o=75;this.i=750;this.j=350;this.l=100;this.m=20;this.G=this.F=0;c(this,this.h);r(this,this.o);t(this,this.i);u(this,this.j);v(this,this.l);x(this,this.m);this.g=!0}}function h(){typeof MathJax!="undefined"?MathJax.typesetPromise():console.log("MathJax not loaded yet!")}function g(a,b){a=a.toPrecision(Math.max(1,Math.min(21,Math.floor(b)))).toLowerCase();a.includes("e+")?a=a.replace("e+","\\times 10^{")+"}":a.includes("e")&&(a=a.replace("e","\\times 10^{")+"}");return a}new z;
