function c(a,b){return Math.sqrt(a*a-2.8*287/(1.4-1)*b)-a}function d(a,b){if(!a.g||b!=a.l){if(!(a.g&&b==a.l||Number.isNaN(b))&&Number.isFinite(b)){b=Math.max(b,1);b=Math.min(b,50);a.l=b;b=a.l;var e=a.W;for(const k of e)k.innerHTML=`${b} Pa`;g(a);h(a);l(a);m(a,a.h*1E3+a.l);n(a)}a.v.value=`${a.l}`}}
function p(a,b){a.g&&b==a.i||(a.g&&b==a.i||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,-50),b=Math.min(b,1E3),a.i=b,b=a.i,a.X.innerHTML=`${b}<sup>o</sup>C = ${b+273} K`,g(a),b=Math.sqrt(1.4*287*(a.i+273)),a.g&&b==a.j||a.g&&b==a.j||Number.isNaN(b)||!Number.isFinite(b)||(a.j=b,h(a),q(a),r(a),t(a),l(a),u(a),v(a),w(a,c(a.j,a.u)),x(a)),q(a),r(a),t(a),u(a),v(a),y(a),z(a),A(a),B(a)),a.B.value=`${a.i}`)}
function C(a,b){a.g&&b==a.h||(a.g&&b==a.h||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,1),b=Math.min(b,1E3),a.h=b,a.Y.innerHTML=`${a.h} kPa`,g(a),h(a),r(a),l(a),v(a),m(a,a.h*1E3+a.l),y(a),z(a),n(a),A(a),B(a)),a.A.value=`${a.h}`)}function h(a){var b=-a.j*a.l/(a.h*1E3*1.4);a.g&&b==a.m||a.g&&b==a.m||Number.isNaN(b)||!Number.isFinite(b)||(a.m=b,q(a),r(a),a.L.innerHTML=`\\[ \\boxed{dV= ${D(a.m)}\\, \\text{m/s}}\\ . \\]`,E(),u(a),v(a))}
function q(a){var b=-(a.i+273)*(1.4-1)*a.m/a.j;a.g&&b==a.C||a.g&&b==a.C||Number.isNaN(b)||!Number.isFinite(b)||(a.C=b,a.J.innerHTML=`\\[ \\boxed{dT=${D(a.C)}\\,\\text{K}}\\ . \\]`,E())}function r(a){var b=-(a.h*1E3)/287/(a.i+273)*a.m/a.j;a.g&&b==a.D||a.g&&b==a.D||Number.isNaN(b)||!Number.isFinite(b)||(a.D=b,a.N.innerHTML=`\\[ \\boxed{d\\rho= ${D(a.D)}\\,\\text{kg/m}^{3}}\\ . \\]`,E())}
function y(a){var b=(a.i+273)*(Math.pow(a.o/(a.h*1E3),(1.4-1)/1.4)-1);a.g&&b==a.u||a.g&&b==a.u||Number.isNaN(b)||!Number.isFinite(b)||(a.u=b,w(a,c(a.j,a.u)),a.P.innerHTML=`\\[ \\boxed{\\Delta T=${D(a.u)}\\,\\text{K}}\\ . \\]`,E(),x(a))}function z(a){var b=a.h;b*=1E3;b=b/287/(a.i+273)*(Math.pow(a.o/b,1/1.4)-1);a.g&&b==a.G||a.g&&b==a.G||Number.isNaN(b)||!Number.isFinite(b)||(a.G=b,a.U.innerHTML=`\\[ \\boxed{\\Delta\\rho=${D(a.G)}\\,\\text{kg/m}^{3}}\\ . \\]`,E())}
function g(a){var b=a.l,e=a.i,k=a.h;a=a.V.getSVGDocument();const F=a?.getElementsByClassName("svg-given-dp");if(F)for(const f of F)f.innerHTML=`${b}`;if(b=a?.getElementsByClassName("svg-given-T"))for(const f of b)f.innerHTML=`${e}`;if(e=a?.getElementsByClassName("svg-given-p"))for(const f of e)f.innerHTML=`${k}`}function t(a){a.H.innerHTML=`\\[ V=a=\\sqrt{\\gamma\\,R\\,T}=\\sqrt{1.4\\times287\\times${a.i+273}}= ${D(a.j)} \\, \\text{m/s}\\ . \\]`;E()}
function l(a){var b=a.l,e=a.h;a.K.innerHTML=`\\[ dV=-\\frac{V\\,dp}{\\gamma\\,p\\,M^{2}}=-\\frac{${D(a.j)}\\times${b}}{1.4\\times${e}\\times10^{3}\\times1^{2}} \\]`;E()}function u(a){var b=a.j;a.I.innerHTML=`\\[ dT=-T\\,\\left(\\gamma-1\\right)\\,M^{2}\\,\\frac{dV}{V}=-${a.i+273}\\times\\left(1.4-1\\right)\\times1^{2}\\times\\left(\\frac{${D(a.m)}}{${D(b)}}\\right) \\]`;E()}
function v(a){var b=a.j;a.M.innerHTML=`\\[ d\\rho=-\\frac{p}{R\\,T}\\,M^{2}\\,\\frac{dV}{V}=-\\frac{${a.h}\\times10^{3}}{287\\times${a.i}}\\times1^{2}\\times\\left(\\frac{${D(a.m)}}{${D(b)}}\\right) \\]`;E()}function m(a,b){a.g&&b==a.o||a.g&&b==a.o||Number.isNaN(b)||!Number.isFinite(b)||(a.o=b,y(a),z(a),n(a),A(a),B(a))}function w(a,b){a.g&&b==a.F||a.g&&b==a.F||Number.isNaN(b)||!Number.isFinite(b)||(a.F=b,a.S.innerHTML=`\\[ \\boxed{\\Delta V=${D(a.F)}\\,\\text{m/s}}\\ . \\]`,E())}
function n(a){a.Z.innerHTML=`\\( p_{2}=p_{1}+\\Delta p=${a.h}\\times10^{3}+${a.l}= ${a.o}\\,\\text{Pa} \\)`;E()}function A(a){a.O.innerHTML=`\\[ \\Delta T=${a.i+273}\\times\\left[\\left(\\frac{${a.o}}{${a.h*1E3}}\\right)^{\\left(1.4-1\\right)/1.4}-1\\right] \\]`;E()}function B(a){var b=a.h;b*=1E3;a.T.innerHTML=`\\[ \\Delta\\rho=\\frac{${b}}{287\\times${a.i+273}}\\left[\\left(\\frac{${a.o}}{${b}}\\right)^{1/1.4}-1\\right] \\]`;E()}
function x(a){var b=a.j,e=a.u;a.R.innerHTML=`\\[ \\Delta V=\\sqrt{${D(b)}^{2}-\\frac{2\\times1.4\\times287}{1.4-1}\\times${D(e)}}-${D(b)} \\]`;E()}
class G{constructor(){this.g=!1;this.v=document.getElementById("dp");this.v.addEventListener("change",()=>d(this,parseFloat(this.v.value)));this.v.step="1";this.v.min="1";this.v.max="50";this.B=document.getElementById("T");this.B.addEventListener("change",()=>p(this,parseFloat(this.B.value)));this.B.step="1";this.B.min="-50";this.B.max="1000";this.A=document.getElementById("p");this.A.addEventListener("change",()=>C(this,parseFloat(this.A.value)));this.A.step="1";this.A.min="1";this.A.max="1000";
this.W=document.getElementsByClassName("given-delta-p");this.X=document.getElementById("given-T");this.Y=document.getElementById("given-p");this.V=document.getElementById("figure");this.H=document.getElementById("V-out");this.K=document.getElementById("dV-eqn");this.L=document.getElementById("dV-out");this.I=document.getElementById("dT-eqn");this.J=document.getElementById("dT-out");this.M=document.getElementById("drho-eqn");this.N=document.getElementById("drho-out");this.Z=document.getElementById("p2-eqn");
this.O=document.getElementById("deltaT-eqn");this.P=document.getElementById("deltaT-out");this.T=document.getElementById("delta_rho-eqn");this.U=document.getElementById("delta_rho-out");this.R=document.getElementById("deltaV-eqn");this.S=document.getElementById("deltaV-out");this.i=this.l=30;this.h=101;this.j=348.9;this.m=-.074;this.C=.026;this.D=2.4E-4;this.o=101030;this.u=.026;this.G=2.5E-4;this.F=-.074;d(this,this.l);p(this,this.i);C(this,this.h);this.g=!0}}
function E(){typeof MathJax!="undefined"&&MathJax.typesetPromise&&MathJax.typesetPromise()}function D(a){a=a.toPrecision(6).toLowerCase();a.includes("e+")?a=a.replace("e+","\\times 10^{")+"}":a.includes("e")&&(a=a.replace("e","\\times 10^{")+"}");return a}new G;
