function c(a,b){a.g&&b==a.l||(a.g&&b==a.l||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,.1),b=Math.min(b,100),a.l=b,d(a),e(a),f(a),g(a)),a.H.value=`${a.l}`)}function h(a,b){a.g&&b==a.B||(a.g&&b==a.B||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,0),b=Math.min(b,2E3),a.B=b,d(a),e(a),f(a),g(a)),a.N.value=`${a.B}`)}
function k(a,b){a.g&&b==a.h||(a.g&&b==a.h||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,1),b=Math.min(b,1E3),a.h=b,l(a,a.h*1E3/287/(a.u+273)),e(a),m(a)),a.P.value=`${a.h}`)}function n(a,b){a.g&&b==a.u||(a.g&&b==a.u||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,-100),b=Math.min(b,1E3),a.u=b,l(a,a.h*1E3/287/(a.u+273)),e(a),m(a)),a.K.value=`${a.u}`)}
function u(a,b){a.g&&b==a.m||(a.g&&b==a.m||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,.1),b=Math.min(b,100),a.m=b,d(a),v(a),f(a),g(a)),a.I.value=`${a.m}`)}function w(a,b){a.g&&b==a.C||(a.g&&b==a.C||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,0),b=Math.min(b,2E3),a.C=b,d(a),v(a),f(a),g(a)),a.O.value=`${a.C}`)}
function x(a,b){a.g&&b==a.i||(a.g&&b==a.i||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,1),b=Math.min(b,1E3),a.i=b,y(a,a.i*1E3/287/(a.v+273)),v(a),z(a)),a.R.value=`${a.i}`)}function A(a,b){a.g&&b==a.v||(a.g&&b==a.v||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,-100),b=Math.min(b,1E3),a.v=b,y(a,a.i*1E3/287/(a.v+273)),v(a),z(a)),a.L.value=`${a.v}`)}
function B(a,b){a.g&&b==a.o||(a.g&&b==a.o||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,.1),b=Math.min(b,100),a.o=b,d(a),C(a),f(a),g(a)),a.J.value=`${a.o}`)}function D(a,b){a.g&&b==a.j||(a.g&&b==a.j||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,1),b=Math.min(b,1E3),a.j=b,E(a,a.j*1E3/287/(a.A+273)),C(a),F(a)),a.S.value=`${a.j}`)}
function G(a,b){a.g&&b==a.A||(a.g&&b==a.A||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,-100),b=Math.min(b,1E3),a.A=b,E(a,a.j*1E3/287/(a.A+273)),C(a),F(a)),a.M.value=`${a.A}`)}function d(a){var b=a.D;var p=a.l,I=a.B,J=a.F,q=a.m,K=a.C,L=a.G,r=a.o;p*=.01;q*=.01;r*=.01;const t=Math.PI/4;b=(b*t*p*p*I+J*t*q*q*K)/(L*t*r*r);a.g&&b==a.T||a.g&&b==a.T||Number.isNaN(b)||!Number.isFinite(b)||(a.T=b,a.W.innerHTML=`$$ \\boxed{V_{3}=${a.T.toPrecision(6)}\\,\\text{m/s}}\\ . $$`,H())}
function l(a,b){a.g&&b==a.D||a.g&&b==a.D||Number.isNaN(b)||!Number.isFinite(b)||(a.D=b,d(a),m(a),f(a),g(a))}function y(a,b){a.g&&b==a.F||a.g&&b==a.F||Number.isNaN(b)||!Number.isFinite(b)||(a.F=b,d(a),z(a),f(a),g(a))}function E(a,b){a.g&&b==a.G||a.g&&b==a.G||Number.isNaN(b)||!Number.isFinite(b)||(a.G=b,d(a),F(a),f(a),g(a))}
function e(a){var b=a.u;a.X.innerHTML=`- ${`\\( T_{1}=${b}^{\\circ}\\text{C}=${b+273}\\,\\text{K} \\)`}, ${`\\( p_{1}=${a.h}\\,\\text{kPa} \\)`}, ${`\\( D_{1}= \u2300${a.l}\\,\\text{cm} \\)`}, ${`\\( V_{1}=${a.B}\\,\\text{m/s} \\)`} (Inlet)`;H()}function v(a){var b=a.v;a.Y.innerHTML=`- ${`\\( T_{2}=${b}^{\\circ}\\text{C}=${b+273}\\,\\text{K} \\)`}, ${`\\( p_{2}=${a.i}\\,\\text{kPa} \\)`}, ${`\\( D_{2}= \u2300${a.m}\\,\\text{cm} \\)`}, ${`\\( V_{2}=${a.C}\\,\\text{m/s} \\)`} (Inlet)`;H()}
function C(a){var b=a.A;a.Z.innerHTML=`- ${`\\( T_{3}=${b}^{\\circ}\\text{C}=${b+273}\\,\\text{K} \\)`}, ${`\\( p_{3}=${a.j}\\,\\text{kPa} \\)`}, ${`\\( D_{3}= \u2300${a.o}\\,\\text{cm} \\)`}, ${"\\( V_{3}=?\\,\\text{m/s} \\)"} (Outlet)`}function m(a){a.U.innerHTML=`$$ \\rho_{1}=\\frac{p_{1}}{R\\,T_{1}}=\\frac{${a.h}\\times10^{3}}{287\\times ${a.u+273}}=${a.D.toPrecision(6)}\\,\\text{kg/m}^{3} $$`;H()}
function z(a){a.aa.innerHTML=`$$ \\rho_{2}=\\frac{p_{2}}{R\\,T_{2}}=\\frac{${a.i}\\times10^{3}}{287\\times ${a.v+273}}=${a.F.toPrecision(6)}\\,\\text{kg/m}^{3} $$`;H()}function F(a){a.ba.innerHTML=`$$ \\rho_{3}=\\frac{p_{1}}{R\\,T_{1}}=\\frac{${a.j}\\times10^{3}}{287\\times ${a.A+273}}=${a.G.toPrecision(6)}\\,\\text{kg/m}^{3} $$`;H()}
function f(a){a.$.innerHTML=`$$ ${a.D.toPrecision(6)}\\times\\frac{\\pi}{4}\\times${a.l}^{2}\\times${a.B} + ${a.F.toPrecision(6)}\\times\\frac{\\pi}{4}\\times${a.m}^{2}\\times${a.C} = ${a.G.toPrecision(6)}\\times\\frac{\\pi}{4}\\times${a.o}^{2}\\times V_{3} $$`;H()}
function g(a){a.V.innerHTML=`$$ V_{3}=\\frac{${a.D.toPrecision(6)}\\times\\frac{\\pi}{4}\\times${a.l}^{2}\\times${a.B} + ${a.F.toPrecision(6)}\\times\\frac{\\pi}{4}\\times${a.m}^{2}\\times${a.C}}{${a.G.toPrecision(6)}\\times\\frac{\\pi}{4} \\times${a.o}^{2}} $$`;H()}
class M{constructor(){this.g=!1;this.H=document.getElementById("D1");this.H.addEventListener("change",()=>c(this,parseFloat(this.H.value)));this.H.step="0.1";this.H.min="0.1";this.H.max="100";this.N=document.getElementById("V1");this.N.addEventListener("change",()=>h(this,parseInt(this.N.value,10)));this.N.step="1";this.N.min="0.0";this.N.max="2000";this.P=document.getElementById("p1");this.P.addEventListener("change",()=>k(this,parseInt(this.P.value,10)));this.P.step="1";this.P.min="1";this.P.max=
"1000";this.K=document.getElementById("T1");this.K.addEventListener("change",()=>n(this,parseInt(this.K.value,10)));this.K.step="1";this.K.min="-100";this.K.max="1000";this.I=document.getElementById("D2");this.I.addEventListener("change",()=>u(this,parseFloat(this.I.value)));this.I.step="0.1";this.I.min="0.1";this.I.max="100";this.O=document.getElementById("V2");this.O.addEventListener("change",()=>w(this,parseInt(this.O.value,10)));this.O.step="1";this.O.min="0.0";this.O.max="2000";this.R=document.getElementById("p2");
this.R.addEventListener("change",()=>x(this,parseInt(this.R.value,10)));this.R.step="1";this.R.min="1";this.R.max="1000";this.L=document.getElementById("T2");this.L.addEventListener("change",()=>A(this,parseInt(this.L.value,10)));this.L.step="1";this.L.min="-100";this.L.max="1000";this.J=document.getElementById("D3");this.J.addEventListener("change",()=>B(this,parseFloat(this.J.value)));this.J.step="0.1";this.J.min="0.1";this.J.max="100";this.S=document.getElementById("p3");this.S.addEventListener("change",
()=>D(this,parseInt(this.S.value,10)));this.S.step="1";this.S.min="1";this.S.max="1000";this.M=document.getElementById("T3");this.M.addEventListener("change",()=>G(this,parseInt(this.M.value,10)));this.M.step="1";this.M.min="-100";this.M.max="1000";this.X=document.getElementById("given1");this.Y=document.getElementById("given2");this.Z=document.getElementById("given3");this.U=document.getElementById("rho1-out");this.aa=document.getElementById("rho2-out");this.ba=document.getElementById("rho3-out");
this.$=document.getElementById("mass-eqn");this.V=document.getElementById("V3-eqn");this.W=document.getElementById("V3-out");this.l=5;this.B=100;this.h=150;this.u=30;this.m=1.5;this.C=150;this.i=75;this.v=30;this.o=9;this.T=0;this.j=90;this.A=30;this.G=this.F=this.D=0;c(this,this.l);h(this,this.B);k(this,this.h);n(this,this.u);u(this,this.m);w(this,this.C);x(this,this.i);A(this,this.v);B(this,this.o);D(this,this.j);G(this,this.A);this.g=!0}}
function H(){typeof MathJax!="undefined"?MathJax.typesetPromise():console.log("MathJax not loaded yet!")}new M;
