function e(a,b){if(!a.g||b!=a.j){if(!(a.g&&b==a.j||Number.isNaN(b))&&Number.isFinite(b)){b=Math.max(b,2);b=Math.min(b,100);a.j=b;f(a);b=a.j;var c=a.J;for(const d of c)d.innerHTML=`${b} kg/kmol`;g(a);h(a)}a.A.value=`${a.j}`}}function k(a,b){a.g&&b==a.i||(a.g&&b==a.i||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,1.1),b=Math.min(b,2),a.i=b,f(a),a.I.innerHTML=`${a.i}`,g(a),h(a)),a.v.value=`${a.i}`)}
function l(a,b){a.g&&b==a.h||(a.g&&b==a.h||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,-50),b=Math.min(b,100),a.h=b,f(a),b=a.h,a.K.innerHTML=`${b}<sup>o</sup>C = ${b+273} K`,g(a),h(a)),a.u.value=`${a.h}`)}
function m(a,b){a.g&&b==a.l||(a.g&&b==a.l||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,10),b=Math.min(b,65),a.l=b,b=1/Math.sin(a.l*Math.PI/180),a.g&&b==a.o||a.g&&b==a.o||Number.isNaN(b)||!Number.isFinite(b)||(a.o=b,f(a),a.D.innerHTML=`\\[ \\boxed{M=${n(a.o)}}\\ . \\]`,p(),h(a)),a.L.innerHTML=`${a.l}`,g(a),a.C.innerHTML=`\\[ M=\\frac{1}{\\sin\\left(\\mu\\right)}=\\frac{1}{\\sin\\left(${a.l}\\right)} \\]`,p()),a.m.value=`${a.l}`)}
function f(a){var b=a.o*Math.sqrt(a.i*8314/a.j*(a.h+273));a.g&&b==a.B||a.g&&b==a.B||Number.isNaN(b)||!Number.isFinite(b)||(a.B=b,a.G.innerHTML=`\\[ \\boxed{V = ${n(a.B)}\\,\\text{m/s}}\\ . \\]`,p())}
function g(a){var b=a.j,c=a.i,d=a.h,r=a.l;a=a.H.getSVGDocument();const q=a?.getElementById("svg-given-gamma");q&&(q.innerHTML=`${c}`);if(c=a?.getElementById("svg-given-molar"))c.innerHTML=`${b} kg/kmol`;if(b=a?.getElementById("svg-given-T"))b.innerHTML=`${d}\u00b0C`;if(d=a?.getElementById("svg-given-mu"))d.innerHTML=`${r}\u00b0`}
function h(a){var b=a.i,c=a.j,d=a.h;a.F.innerHTML=`\\[ V=M\\,a=M\\times\\sqrt{\\gamma\\,\\frac{R_{u}}{\\hat{m}}\\,T}=${n(a.o)}\\times\\sqrt{${b}\\times\\frac{8314}{${c}}\\times${d+273}} \\]`;p()}
class t{g;j;A;i;v;h;u;l;m;o;B;J;I;K;L;H;C;D;F;G;constructor(){this.g=!1;this.A=document.getElementById("molar");this.A.addEventListener("change",()=>e(this,parseFloat(this.A.value)));this.A.step="0.1";this.A.min="2";this.A.max="100";this.v=document.getElementById("gamma");this.v.addEventListener("change",()=>k(this,parseFloat(this.v.value)));this.v.step="0.01";this.v.min="1.1";this.v.max="2";this.u=document.getElementById("T");this.u.addEventListener("change",()=>l(this,parseFloat(this.u.value)));
this.u.step="1";this.u.min="-50";this.u.max="100";this.m=document.getElementById("mu");this.m.addEventListener("change",()=>m(this,parseFloat(this.m.value)));this.m.step="1";this.m.min="10";this.m.max="65";this.J=document.getElementsByClassName("given-molar");this.I=document.getElementById("given-gamma");this.K=document.getElementById("given-T");this.L=document.getElementById("given-mu");this.H=document.getElementById("figure");this.C=document.getElementById("M-eqn");this.D=document.getElementById("M-out");
this.F=document.getElementById("V-eqn");this.G=document.getElementById("V-out");this.j=44;this.i=1.67;this.h=10;this.l=45;this.o=1.4;this.B=623.2;e(this,this.j);k(this,this.i);l(this,this.h);m(this,this.l);this.g=!0}}function p(){typeof MathJax!="undefined"&&MathJax.typesetPromise&&MathJax.typesetPromise()}function n(a){a=a.toPrecision(6).toLowerCase();a.includes("e+")?a=a.replace("e+","\\times 10^{")+"}":a.includes("e")&&(a=a.replace("e","\\times 10^{")+"}");return a}new t;
