function c(a,b){a.g&&b==a.j||(a.g&&b==a.j||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,.1),b=Math.min(b,1E3),a.j=b,d(a),a.M.innerHTML=`\\( V_{1} = ${a.j}\\,\\text{m/s} \\)`,e(),f(a),h(a)),a.A.value=`${a.j}`)}function k(a,b){a.g&&b==a.h||(a.g&&b==a.h||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,.1),b=Math.min(b,1E3),a.h=b,d(a),l(a,a.m*1E6/287/(a.h+273)),b=a.h,a.K.innerHTML=`\\( T_{1} = ${b}^{\\circ}\\,\\text{C} = ${b+273}\\,\\text{K} \\)`,e(),f(a),h(a),m(a)),a.F.value=`${a.h}`)}
function n(a,b){a.g&&b==a.m||(a.g&&b==a.m||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,.01),b=Math.min(b,1E3),a.m=b,l(a,a.m*1E6/287/(a.h+273)),a.O.innerHTML=`\\( p_{1} = ${a.m}\\,\\text{MPa} \\)`,e(),m(a)),a.C.value=`${a.m}`)}function p(a,b){a.g&&b==a.l||(a.g&&b==a.l||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,.1),b=Math.min(b,1E3),a.l=b,d(a),a.N.innerHTML=`\\( V_{e} = ${a.l}\\,\\text{m/s} \\)`,e(),f(a),h(a)),a.B.value=`${a.l}`)}
function q(a,b){a.g&&b==a.i||(a.g&&b==a.i||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,.1),b=Math.min(b,1E3),a.i=b,d(a),r(a,a.o*1E6/287/(a.i+273)),b=a.i,a.L.innerHTML=`\\( T_{e} = ${b}^{\\circ}\\,\\text{C} = ${b+273}\\,\\text{K} \\)`,e(),f(a),h(a),t(a)),a.v.value=`${a.i}`)}
function u(a,b){a.g&&b==a.o||(a.g&&b==a.o||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,.01),b=Math.min(b,1E3),a.o=b,r(a,a.o*1E6/287/(a.i+273)),a.P.innerHTML=`\\( p_{e} = ${a.o}\\,\\text{MPa} \\)`,e(),t(a)),a.D.value=`${a.o}`)}
function d(a){var b=a.l;var g=a.j;b=1005*(a.i+273)+b*b/2-1005*(a.h+273)-g*g/2;if(!(a.g&&b==a.u||a.g&&b==a.u||Number.isNaN(b))&&Number.isFinite(b)){a.u=b;h(a);a.U.innerText=a.u<0?"negative":"positive";b=a.u;g=a.T;for(const w of g)w.innerText=b<0?"removed":"added";a.S.innerHTML=`$$ \\boxed{\\frac{\\dot{q}}{\\dot{m}}=${v(Math.abs(a.u))}\\,\\text{J/kg}}\\ . $$`;e()}}
function l(a,b){a.g&&b==a.G||a.g&&b==a.G||Number.isNaN(b)||!Number.isFinite(b)||(a.G=b,a.W.innerHTML=`$$ \\boxed{\\rho_{1}=${v(a.G)}\\,\\text{kg/m}^{3}}\\ . $$`,e())}function r(a,b){a.g&&b==a.H||a.g&&b==a.H||Number.isNaN(b)||!Number.isFinite(b)||(a.H=b,a.Y.innerHTML=`$$ \\boxed{\\rho_{e}=${v(a.H)}\\,\\text{kg/m}^{3}}\\ . $$`,e())}
function f(a){a.J.innerHTML=`$$ ${1005} \\times ${a.h+273} + \\frac{${a.j}^{2}}{2} + \\frac{\\dot{q}}{\\dot{m}} = ${1005} \\times ${a.i+273} + \\frac{${a.l}^{2}}{2} $$`;e()}function h(a){a.R.innerHTML=`$$ \\frac{\\dot{q}}{\\dot{m}} = ${1005} \\times ${a.i+273} + \\frac{${a.l}^{2}}{2} - ${1005} \\times ${a.h+273} - \\frac{${a.j}^{2}}{2} = ${v(a.u)}\\ . $$`;e()}function m(a){a.V.innerHTML=`$$ \\rho_{1}=\\frac{p_{1}}{R\\,T_{1}}=\\frac{${a.m}\\times10^{6}}{${287}\\times${a.h+273}} $$`;e()}
function t(a){a.X.innerHTML=`$$ \\rho_{e} = \\frac{p_{e}}{R\\,T_{e}} = \\frac{${a.o} \\times 10^{6}}{${287} \\times ${a.i+273}} $$`;e()}
class x{constructor(){this.g=!1;this.A=document.getElementById("V1");this.A.addEventListener("change",()=>c(this,parseFloat(this.A.value)));this.A.step="0.1";this.A.min="0.1";this.A.max="1000";this.F=document.getElementById("T1");this.F.addEventListener("change",()=>k(this,parseFloat(this.F.value)));this.F.step="0.1";this.F.min="0.1";this.F.max="1000";this.C=document.getElementById("p1");this.C.addEventListener("change",()=>n(this,parseFloat(this.C.value)));this.C.step="0.01";this.C.min="0.01";this.C.max=
"1000";this.B=document.getElementById("Ve");this.B.addEventListener("change",()=>p(this,parseFloat(this.B.value)));this.B.step="0.1";this.B.min="0.1";this.B.max="1000";this.v=document.getElementById("Te");this.v.addEventListener("change",()=>q(this,parseFloat(this.v.value)));this.v.step="0.1";this.v.min="0.1";this.v.max="1000";this.D=document.getElementById("pe");this.D.addEventListener("change",()=>u(this,parseFloat(this.D.value)));this.D.step="0.01";this.D.min="0.01";this.D.max="1000";this.M=document.getElementById("given-V1");
this.K=document.getElementById("given-T1");this.O=document.getElementById("given-p1");this.N=document.getElementById("given-Ve");this.L=document.getElementById("given-Te");this.P=document.getElementById("given-pe");this.I=document.getElementById("cp-out");this.J=document.getElementById("energy-eqn");this.R=document.getElementById("heat-flow-eqn");this.U=document.getElementById("q-m-sign");this.T=document.getElementsByClassName("q-m-dir");this.S=document.getElementById("heat-flow-out");this.V=document.getElementById("rho1-eqn");
this.W=document.getElementById("rho1-out");this.X=document.getElementById("rhoe-eqn");this.Y=document.getElementById("rhoe-out");this.j=120;this.h=225;this.m=2.5;this.l=30;this.i=80;this.o=2.45;this.u=-152475;this.G=17.5;this.H=24.2;c(this,this.j);k(this,this.h);n(this,this.m);p(this,this.l);q(this,this.i);u(this,this.o);this.I.innerHTML="\\( c_{p}=1005\\,\\text{J/kg-K} \\)";e();this.g=!0}}function e(){typeof MathJax!="undefined"&&MathJax.typesetPromise()}
function v(a){a=a.toPrecision(6).toLowerCase();a.includes("e+")?a=a.replace("e+","\\times 10^{")+"}":a.includes("e")&&(a=a.replace("e","\\times 10^{")+"}");return a}new x;
