const g=[];function h(a){return{plugins:{legend:!1},scales:{x:{beginAtZero:!1,title:{text:"V",display:!0,font:{size:16}}},y:{beginAtZero:!0,title:{text:a,display:!0,font:{size:16}}}}}}
const k=document.getElementById("dp_dx-out"),l=[],n=new Chart(k,{type:"line",data:{labels:g,datasets:[{label:"dp/dx",data:l,borderWidth:4,pointStyle:!1,cubicInterpolationMode:"monotone"}]},options:h("dp/dx")}),p=document.getElementById("dV_dx-out"),q=[],r=new Chart(p,{type:"line",data:{labels:g,datasets:[{label:"dV/dx",data:q,borderWidth:4,pointStyle:!1,cubicInterpolationMode:"monotone"}]},options:h("dV/dx")}),t=document.getElementById("drho_dx-out"),u=[],v=new Chart(t,{type:"line",data:{labels:g,
datasets:[{label:"d\u03c1/dx",data:u,borderWidth:4,pointStyle:!1,cubicInterpolationMode:"monotone"}]},options:h("d\u03c1/dx")});function w(a,b){b=(b-a)/500;for(let e=0;e<500;e++)g[e]=Math.round((a+b*e)*100)/100}function x(a,b){a.g&&b==a.m||(a.g&&b==a.m||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,.01),b=Math.min(b,100),a.m=b,a.G.innerText=`${a.m}`,y(a),z(a),A(a)),a.F.value=`${a.m}`)}
function B(a,b){a.g&&b==a.i||(a.g&&b==a.i||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,1),b=Math.min(b,1E3),a.i=b,C(a,a.i*1E3/287/(a.h+273)),a.M.innerText=`${a.i}`,y(a),z(a),A(a)),a.C.value=`${a.i}`)}function D(a,b){a.g&&b==a.h||(a.g&&b==a.h||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,-50),b=Math.min(b,1E3),a.h=b,C(a,a.i*1E3/287/(a.h+273)),a.H.innerText=`${a.h}`,a.I.innerText=`${a.h+273}`,y(a),z(a),A(a)),a.u.value=`${a.h}`)}
function E(a,b){a.g&&b==a.o||(a.g&&b==a.o||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,-50),b=Math.min(b,50),a.o=b,a.J.innerText=`${a.o}`,y(a),z(a),A(a)),a.v.value=`${a.o}`)}function F(a,b){if(!a.g||b!=a.l){if(!(a.g&&b==a.l||Number.isNaN(b))&&Number.isFinite(b)){b=Math.max(b,1);b=Math.min(b,1E3);a.g&&(b=Math.min(b,a.j-1));a.l=b;b=a.l;var e=a.L;for(const d of e)d.innerText=`${b}`;y(a);z(a);A(a)}a.B.value=`${a.l}`}}
function G(a,b){if(!a.g||b!=a.j){if(!(a.g&&b==a.j||Number.isNaN(b))&&Number.isFinite(b)){b=Math.max(b,1);b=Math.min(b,1E3);a.g&&(b=Math.max(b,a.l+1));a.j=b;b=a.j;var e=a.K;for(const d of e)d.innerText=`${b}`;y(a);z(a);A(a)}a.A.value=`${a.j}`}}function C(a,b){a.g&&b==a.D||a.g&&b==a.D||Number.isNaN(b)||!Number.isFinite(b)||(a.D=b,y(a),z(a),A(a))}
function y(a){var b=a.h,e=a.o,d=a.i,f=a.D,m=a.m;b+=273;d*=1E3;w(a.l,a.j);for(a=0;a<500;a++){const c=g[a];l[a]=-b*c*c*1005*d*f/(m*(b*c*c*1005*f+(-b*1005-c*c)*d)/e)}n.update()}function z(a){var b=a.h,e=a.o,d=a.i,f=a.D,m=a.m;b+=273;d*=1E3;w(a.l,a.j);for(a=0;a<500;a++){const c=g[a];q[a]=b*c*1005*d/(m*(b*c*c*1005*f+(-b*1005-c*c)*d)/e)}r.update()}
function A(a){var b=a.h,e=a.o,d=a.i,f=a.D,m=a.m;b+=273;d*=1E3;w(a.l,a.j);for(a=0;a<500;a++){const c=g[a];u[a]=-(b*c*c*1005*f*f-c*c*d*f)/(m*(b*c*c*1005*f+(-b*1005-c*c)*d)/e)}v.update()}
class H{constructor(){this.g=!1;this.F=document.getElementById("A");this.F.addEventListener("change",()=>x(this,parseFloat(this.F.value)));this.F.step="0.01";this.F.min="0.01";this.F.max="100";this.C=document.getElementById("p");this.C.addEventListener("change",()=>B(this,parseFloat(this.C.value)));this.C.step="0.1";this.C.min="1";this.C.max="1000";this.u=document.getElementById("T");this.u.addEventListener("change",()=>D(this,parseFloat(this.u.value)));this.u.step="0.1";this.u.min="-50";this.u.max=
"1000";this.v=document.getElementById("dA_dx");this.v.addEventListener("change",()=>E(this,parseFloat(this.v.value)));this.v.step="1";this.v.min="-50.0";this.v.max="50.0";this.B=document.getElementById("minV");this.B.addEventListener("change",()=>F(this,parseFloat(this.B.value)));this.B.step="1";this.B.min="1";this.B.max="1000";this.A=document.getElementById("maxV");this.A.addEventListener("change",()=>G(this,parseFloat(this.A.value)));this.A.step="1";this.A.min="1";this.A.max="1000";this.G=document.getElementById("given-A");
this.M=document.getElementById("given-p");this.H=document.getElementById("given-T");this.I=document.getElementById("given-TK");this.J=document.getElementById("given-dA_dx");this.L=document.getElementsByClassName("given-minV");this.K=document.getElementsByClassName("given-maxV");document.getElementById("dp_dx-out");document.getElementById("dV_dx-out");document.getElementById("drho_dx-out");this.m=.1;this.i=120;this.h=15;this.o=.1;this.l=50;this.j=300;this.D=1;x(this,this.m);B(this,this.i);D(this,this.h);
E(this,this.o);F(this,this.l);G(this,this.j);this.g=!0}}new H;
