const f=[];function g(a){return{plugins:{legend:!1},scales:{x:{beginAtZero:!1,title:{text:"V",display:!0,font:{size:16}}},y:{beginAtZero:!0,title:{text:a,display:!0,font:{size:16}}}}}}
const h=document.getElementById("dp_dx-out"),k=[],l=new Chart(h,{type:"line",data:{labels:f,datasets:[{label:"dp/dx",data:k,borderWidth:4,pointStyle:!1,cubicInterpolationMode:"monotone"}]},options:g("dp/dx")}),m=document.getElementById("dV_dx-out"),n=[],p=new Chart(m,{type:"line",data:{labels:f,datasets:[{label:"dV/dx",data:n,borderWidth:4,pointStyle:!1,cubicInterpolationMode:"monotone"}]},options:g("dV/dx")}),q=document.getElementById("drho_dx-out"),r=[],t=new Chart(q,{type:"line",data:{labels:f,
datasets:[{label:"d\u03c1/dx",data:r,borderWidth:4,pointStyle:!1,cubicInterpolationMode:"monotone"}]},options:g("d\u03c1/dx")});function u(a,b){b=(b-a)/500;for(let c=0;c<500;c++)f[c]=Math.round((a+b*c)*100)/100}function v(a,b){a.g&&b==a.l||(a.g&&b==a.l||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,.01),b=Math.min(b,100),a.l=b,a.F.innerText=`${a.l}`,w(a),x(a),y(a)),a.C.value=`${a.l}`)}
function z(a,b){a.g&&b==a.o||(a.g&&b==a.o||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,1),b=Math.min(b,1E3),a.o=b,a.L.innerText=`${a.o}`,w(a),y(a)),a.B.value=`${a.o}`)}function A(a,b){if(!a.g||b!=a.h){if(!(a.g&&b==a.h||Number.isNaN(b))&&Number.isFinite(b)){b=Math.max(b,-50);b=Math.min(b,1E3);if(a.g){var c=a.i;b=c*c/(1.4*287*(b+273))<.9999?b:c*c/(.9999*1.4*287)-273}a.h=b;a.G.innerText=`${a.h}`;a.H.innerText=`${a.h+273}`;w(a);x(a);y(a)}a.D.value=`${a.h}`}}
function B(a,b){a.g&&b==a.m||(a.g&&b==a.m||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,-50),b=Math.min(b,50),a.m=b,a.I.innerText=`${a.m}`,w(a),x(a),y(a)),a.u.value=`${a.m}`)}function C(a,b){if(!a.g||b!=a.j){if(!(a.g&&b==a.j||Number.isNaN(b))&&Number.isFinite(b)){b=Math.max(b,1);b=Math.min(b,1E3);a.g&&(b=Math.min(b,a.i-1));a.j=b;b=a.j;var c=a.K;for(const d of c)d.innerText=`${b}`;w(a);x(a);y(a)}a.A.value=`${a.j}`}}
function D(a,b){if(!a.g||b!=a.i){if(!(a.g&&b==a.i||Number.isNaN(b))&&Number.isFinite(b)){b=Math.max(b,1);b=Math.min(b,1E3);if(a.g){b=Math.max(b,a.j+1);var c=Math.sqrt(1.4*287*(a.h+273));b/c>.9999&&(b=.9999*c)}a.i=b;b=a.i;c=a.J;for(const d of c)d.innerText=`${b}`;w(a);x(a);y(a)}a.v.value=`${a.i}`}}function w(a){var b=a.h,c=a.m,d=a.o,e=a.l;b+=273;d*=1E3;u(a.j,a.i);a=1.4*287*b;c/=e;for(e=0;e<500;e++)b=f[e],b=b*b/a,k[e]=c*b*d*1.4/(1-b);l.update()}
function x(a){var b=a.h,c=a.m,d=a.l;b+=273;u(a.j,a.i);a=1.4*287*b;c/=d;for(d=0;d<500;d++)b=f[d],n[d]=-c*b/(1-b*b/a);p.update()}function y(a){var b=a.h,c=a.m,d=a.o,e=a.l;b+=273;d*=1E3;u(a.j,a.i);a=1.4*287*b;c/=e;b=d/287/b;for(d=0;d<500;d++)e=f[d],e=e*e/a,r[d]=c*e*b/(1-e);t.update()}
class E{constructor(){this.g=!1;this.C=document.getElementById("A");this.C.addEventListener("change",()=>v(this,parseFloat(this.C.value)));this.C.step="0.01";this.C.min="0.01";this.C.max="100";this.B=document.getElementById("p");this.B.addEventListener("change",()=>z(this,parseFloat(this.B.value)));this.B.step="0.1";this.B.min="1";this.B.max="1000";this.D=document.getElementById("T");this.D.addEventListener("change",()=>A(this,parseFloat(this.D.value)));this.D.step="0.1";this.D.min="-50";this.D.max=
"1000";this.u=document.getElementById("dA_dx");this.u.addEventListener("change",()=>B(this,parseFloat(this.u.value)));this.u.step="1";this.u.min="-50.0";this.u.max="50.0";this.A=document.getElementById("minV");this.A.addEventListener("change",()=>C(this,parseFloat(this.A.value)));this.A.step="1";this.A.min="1";this.A.max="1000";this.v=document.getElementById("maxV");this.v.addEventListener("change",()=>D(this,parseFloat(this.v.value)));this.v.step="1";this.v.min="1";this.v.max="1000";this.F=document.getElementById("given-A");
this.L=document.getElementById("given-p");this.G=document.getElementById("given-T");this.H=document.getElementById("given-TK");this.I=document.getElementById("given-dA_dx");this.K=document.getElementsByClassName("given-minV");this.J=document.getElementsByClassName("given-maxV");document.getElementById("dp_dx-out");document.getElementById("dV_dx-out");document.getElementById("drho_dx-out");this.l=.1;this.o=120;this.h=15;this.m=.1;this.j=50;this.i=300;v(this,this.l);z(this,this.o);A(this,this.h);B(this,
this.m);C(this,this.j);D(this,this.i);this.g=!0}}new E;
