function c(a,b){a.g&&b==a.i||(a.g&&b==a.i||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,.1),b=Math.min(b,100),a.i=b,d(a),e(a),f(a),a.P.innerHTML=`\\( \\dot{m}=${a.i}\\,\\text{kg/s} \\)`,g(),h(a),k(a),l(a),m(a)),a.C.value=`${a.i}`)}function n(a,b){a.g&&b==a.o||(a.g&&b==a.o||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,1),b=Math.min(b,1E3),a.o=b,f(a),a.R.innerHTML=`\\( p_{\\text{amb}}=p_{0}=${a.o}\\,\\text{kPa} \\)`,g(),m(a)),a.D.value=`${a.o}`)}
function p(a,b){a.g&&b==a.l||(a.g&&b==a.l||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,-50),b=Math.min(b,1E3),a.l=b,d(a),b=a.l,a.N.innerHTML=`\\( T_{\\text{amb}}=T_{0}=${b}^{\\circ}\\,\\text{C}=${b+273}\\,\\text{K} \\)`,g(),h(a),k(a)),a.A.value=`${a.l}`)}function q(a,b){a.g&&b==a.h||(a.g&&b==a.h||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,1),b=Math.min(b,5E3),a.h=b,d(a),e(a),f(a),a.O.innerHTML=`\\( V_{e}=${a.h}\\,\\text{m/s} \\)`,g(),h(a),k(a),l(a),m(a)),a.B.value=`${a.h}`)}
function r(a,b){a.g&&b==a.j||(a.g&&b==a.j||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,1),b=Math.min(b,1E3),a.j=b,t(a,a.j*1E3/(287*a.u)),f(a),a.S.innerHTML=`\\( p_{e}=${a.j}\\,\\text{kPa} \\)`,g(),u(a),m(a)),a.F.value=`${a.j}`)}function v(a,b){a.g&&b==a.m||(a.g&&b==a.m||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,1),b=Math.min(b,5E3),a.m=b,d(a),a.T.innerHTML=`\\( \\dot{q}=${a.m}\\,\\text{kW} \\)`,g(),h(a),k(a)),a.G.value=`${a.m}`)}
function d(a){var b=a.i;var x=a.h;b=(b*1005*(a.l+273)+a.m*1E3-b*x*x/2)/(b*1005);a.g&&b==a.u||a.g&&b==a.u||Number.isNaN(b)||!Number.isFinite(b)||(a.u=b,t(a,a.j*1E3/(287*a.u)),k(a),u(a))}function e(a){var b=a.i/a.v/a.h;a.g&&b==a.H||a.g&&b==a.H||Number.isNaN(b)||!Number.isFinite(b)||(a.H=b,f(a),a.K.innerHTML=`$$ \\boxed{A_{e}=${w(a.H)}\\,\\text{m}^{2}}\\ . $$`,g(),m(a))}
function f(a){var b=a.i*a.h+(a.j-a.o)*1E3*a.H;a.g&&b==a.I||a.g&&b==a.I||Number.isNaN(b)||!Number.isFinite(b)||(a.I=b,a.W.innerHTML=`$$ \\boxed{\\text{Thrust}=${w(a.I)}\\,\\text{N}}\\ . $$`,g())}function t(a,b){a.g&&b==a.v||a.g&&b==a.v||Number.isNaN(b)||!Number.isFinite(b)||(a.v=b,e(a),u(a),l(a))}function u(a){var b=a.v;a.U.innerHTML=`$$ \\rho_{e}=\\frac{p_{e}}{R\\,T_{e}}=\\frac{${a.j}\\times10^{3}}{${287}\\times${w(a.u)}}=${w(b)}\\,\\text{kg/m}^{3} $$`;g()}
function h(a){var b=a.i;a.M.innerHTML=`$$ ${b}\\times${1005}\\times${a.l+273+273}+${a.m}\\times10^{3}=${b}\\times${1005}\\times T_{e}+${b}\\times\\frac{${a.h}^{2}}{2}+0 $$`;g()}function k(a){var b=a.i;a.L.innerHTML=`$$ T_{e}=\\frac{${b}\\times${1005}\\times${a.l+273}+${a.m}\\times10^{3}-${b}\\times\\frac{${a.h}^{2}}{2}}{3\\times${1005}}=${w(a.u)}\\,\\text{K}\\ . $$`;g()}function l(a){var b=a.h;a.J.innerHTML=`$$ A_{e}=\\frac{\\dot{m}}{\\rho_{e}V_{e}}=\\frac{${a.i}}{${w(a.v)}\\times ${b}} $$`;g()}
function m(a){a.V.innerHTML=`$$ \\text{Thrust}=${a.i}\\times${a.h}+\\left(${a.j}\\times10^{3}-${a.o}\\times10^{3}\\right)\\times${w(a.H)} $$`;g()}
class y{constructor(){this.g=!1;this.C=document.getElementById("m");this.C.addEventListener("change",()=>c(this,parseFloat(this.C.value)));this.C.step="0.1";this.C.min="0.1";this.C.max="100";this.D=document.getElementById("p0");this.D.addEventListener("change",()=>n(this,parseFloat(this.D.value)));this.D.step="0.1";this.D.min="1";this.D.max="1000";this.A=document.getElementById("T0");this.A.addEventListener("change",()=>p(this,parseFloat(this.A.value)));this.A.step="0.1";this.A.min="-50";this.A.max=
"1000";this.B=document.getElementById("Ve");this.B.addEventListener("change",()=>q(this,parseFloat(this.B.value)));this.B.step="0.1";this.B.min="1";this.B.max="5000";this.F=document.getElementById("pe");this.F.addEventListener("change",()=>r(this,parseFloat(this.F.value)));this.F.step="0.1";this.F.min="1";this.F.max="1000";this.G=document.getElementById("q");this.G.addEventListener("change",()=>v(this,parseFloat(this.G.value)));this.G.step="0.1";this.G.min="1";this.G.max="5000";this.P=document.getElementById("given-m");
this.R=document.getElementById("given-p0");this.N=document.getElementById("given-T0");this.O=document.getElementById("given-Ve");this.S=document.getElementById("given-pe");this.T=document.getElementById("given-q");this.U=document.getElementById("rho-e-out");this.M=document.getElementById("energy-eqn");this.L=document.getElementById("Te-out");this.J=document.getElementById("Ae-eqn");this.K=document.getElementById("Ae-out");this.V=document.getElementById("thrust-eqn");this.W=document.getElementById("thrust-out");
this.i=3;this.o=100;this.l=30;this.h=500;this.j=140;this.m=600;this.u=377;this.v=1.3;this.H=.005;this.I=1685.8;c(this,this.i);n(this,this.o);p(this,this.l);q(this,this.h);r(this,this.j);v(this,this.m);this.g=!0}}function g(){typeof MathJax!="undefined"?MathJax.typesetPromise():console.log("MathJax not loaded yet!")}function w(a){a=a.toPrecision(6).toLowerCase();a.includes("e+")?a=a.replace("e+","\\times 10^{")+"}":a.includes("e")&&(a=a.replace("e","\\times 10^{")+"}");return a}new y;
