function e(a){switch(a){case "methane":return 1.32;case "air":return 1.404;case "argon":return 1.667;case "carbon dioxide":return 1.3;case "freon-12":return 1.139;case "helium":return 1.667;case "hydrogen":return 1.407;case "xenon":return 1.667}}function f(a){switch(a){case "methane":return 16;case "air":return 28.96;case "argon":return 39.94;case "carbon dioxide":return 44.01;case "freon-12":return 120.9;case "helium":return 4.003;case "hydrogen":return 2.016;case "xenon":return 131.3}}
function h(a,b){if(!a.g||b!=a.u){if((!a.g||b!=a.u)&&"methane;air;argon;carbon dioxide;freon-12;helium;hydrogen;xenon".split(";").includes(b)){a.u=b;b=e(a.u);if(!(a.g&&b==a.K||a.g&&b==a.K||Number.isNaN(b))&&Number.isFinite(b)){a.K=b;b=a.K;var d=a.W;for(var c of d)c.innerText=`${b}`}c=f(a.u);if(!(a.g&&c==a.A||a.g&&c==a.A||Number.isNaN(c))&&Number.isFinite(c)){a.A=c;c=8314/a.A;a.g&&c==a.I||a.g&&c==a.I||Number.isNaN(c)||!Number.isFinite(c)||(a.I=c,k(a),l(a),m(a));c=a.A;b=a.X;for(var g of b)g.innerText=
`${c}`;l(a)}g=a.u;c=a.R;for(const E of c)E.innerText=g}a.N.value=`${a.u}`}}function n(a,b){a.g&&b==a.o||(a.g&&b==a.o||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,.1),b=Math.min(b,100),a.o=b,p(a),a.S.innerText=`${a.o}`,q(a)),a.C.value=`${a.o}`)}
function r(a,b){a.g&&b==a.l||(a.g&&b==a.l||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,173),b=Math.min(b,1E3),a.l=b,b=a.l,a.g&&b==a.J||a.g&&b==a.J||Number.isNaN(b)||!Number.isFinite(b)||(a.J=b,a.U.innerText=`${a.J}`),k(a),a.T.innerText=`${a.l}`,m(a)),a.D.value=`${a.l}`)}function t(a,b){a.g&&b==a.i||(a.g&&b==a.i||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,1),b=Math.min(b,1E3),a.i=b,k(a),u(a),a.Y.innerText=`${a.i}`,m(a),v(a)),a.H.value=`${a.i}`)}
function w(a,b){a.g&&b==a.h||(a.g&&b==a.h||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,.1),b=Math.min(b,1E3),a.h=b,p(a),x(a),y(a),a.V.innerText=`${a.h}`,q(a),z(a),A(a)),a.F.value=`${a.h}`)}function B(a,b){a.g&&b==a.m||(a.g&&b==a.m||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,.1),b=Math.min(b,1E3),a.m=b,x(a),y(a),z(a),A(a)),a.G.value=`${a.m}`)}
function p(a){var b=a.j;var d=a.o;const c=Math.PI/4;d*=.01;b=c*d*d*b*a.h;a.g&&b==a.v||a.g&&b==a.v||Number.isNaN(b)||!Number.isFinite(b)||(a.v=b,x(a),q(a),z(a))}function k(a){var b=a.i*1E3/a.I/a.l;a.g&&b==a.j||a.g&&b==a.j||Number.isNaN(b)||!Number.isFinite(b)||(a.j=b,p(a),y(a),u(a),m(a),q(a),A(a),v(a))}function u(a){var b=a.B*a.i/a.j;a.g&&b==a.L||a.g&&b==a.L||Number.isNaN(b)||!Number.isFinite(b)||(a.L=b,a.O.innerHTML=`\\[ \\boxed{p_{2}=${C(a.L,6)}\\,\\text{kPa}}\\ . \\]`,D())}
function x(a){var b=a.m;var d=a.h;b=a.v/2*(b*b-d*d);a.g&&b==a.M||a.g&&b==a.M||Number.isNaN(b)||!Number.isFinite(b)||(a.M=b,a.ba.innerHTML=`\\[ \\boxed{\\dot{q}=${C(a.M,6)}\\,\\text{J/s}}\\ . \\]`,D())}function y(a){var b=a.j*a.h/a.m;a.g&&b==a.B||a.g&&b==a.B||Number.isNaN(b)||!Number.isFinite(b)||(a.B=b,u(a),A(a),v(a))}function l(a){a.P.innerHTML=`\\[ R=\\frac{R_{u}}{\\hat{m}}=\\frac{8314}{${a.A}} = ${C(a.I,6)}\\, \\text{J/kg-K}\\ . \\]`;D()}
function m(a){var b=a.l,d=a.j;a.ca.innerHTML=`\\[ \\rho_{1}=\\frac{p_{1}}{R\\,T_{1}}=\\frac{${a.i}\\times10^{3}}{${C(a.I,6)}\\times${b}}=${C(d,6)}\\,\\text{kg/m}^{3}\\ . \\]`;D()}function q(a){var b=a.j,d=a.o,c=a.h,g=a.v;d*=.01;a.Z.innerHTML=`\\[ \\dot{m}=\\rho_{1}A_{1}V_{1}=${C(b,6)}\\times\\frac{\\pi}{4}${C(d,3)}^{2}\\times${c}=${C(g,6)}\\,\\text{kg/s}\\ . \\]`;D()}function z(a){var b=a.m,d=a.h;a.aa.innerHTML=`\\[ \\dot{q}=\\frac{${C(a.v,6)}}{2}\\times\\left(${b}^{2}-${d}^{2}\\right) \\]`;D()}
function A(a){var b=a.h,d=a.m,c=a.B;a.da.innerHTML=`\\[ \\rho_{2}=\\frac{${C(a.j,6)}\\times${b}}{${d}}=${C(c,6)}\\,\\text{kg/m}^{3} \\]`;D()}function v(a){var b=a.i,d=a.j;a.$.innerHTML=`\\[ p_{2}=\\rho_{2}\\times\\frac{p_{1}}{\\rho_{1}}=${C(a.B,6)}\\cdot\\frac{${b}\\times10^{3}}{${C(d,6)}} \\]`;D()}
class F{constructor(){this.g=!1;this.N=document.getElementById("gas");this.N.addEventListener("change",()=>h(this,this.N.value));this.C=document.getElementById("D");this.C.addEventListener("change",()=>n(this,parseFloat(this.C.value)));this.C.step="0.1";this.C.min="0.1";this.C.max="100";this.D=document.getElementById("T1");this.D.addEventListener("change",()=>r(this,parseFloat(this.D.value)));this.D.step="0.1";this.D.min="173";this.D.max="1000";this.H=document.getElementById("p1");this.H.addEventListener("change",
()=>t(this,parseFloat(this.H.value)));this.H.step="0.1";this.H.min="1";this.H.max="1000";this.F=document.getElementById("V1");this.F.addEventListener("change",()=>w(this,parseFloat(this.F.value)));this.F.step="0.1";this.F.min="0.1";this.F.max="1000";this.G=document.getElementById("V2");this.G.addEventListener("change",()=>B(this,parseFloat(this.G.value)));this.G.step="0.1";this.G.min="0.1";this.G.max="1000";this.W=document.getElementsByClassName("given-gamma");this.X=document.getElementsByClassName("given-molar");
this.R=document.getElementsByClassName("gas-out");this.S=document.getElementById("given-D");this.T=document.getElementById("given-T1");this.Y=document.getElementById("given-p1");this.V=document.getElementById("given-V1");this.U=document.getElementById("given-T2");this.P=document.getElementById("R-out");this.ca=document.getElementById("rho1-out");this.Z=document.getElementById("m-out");this.aa=document.getElementById("q-eqn");this.ba=document.getElementById("q-out");this.da=document.getElementById("rho2-out");
this.$=document.getElementById("p2-eqn");this.O=document.getElementById("p2-out");this.u="methane";this.o=4;this.l=200;this.i=250;this.h=30;this.m=35;this.K=1.3;this.A=16;this.J=200;this.I=519.6;this.j=2.4;this.v=.0907;this.M=14.7;this.B=2.1;this.L=214285.7;h(this,this.u);n(this,this.o);r(this,this.l);t(this,this.i);w(this,this.h);B(this,this.m);this.g=!0}}function D(){typeof MathJax!="undefined"&&MathJax.typesetPromise&&MathJax.typesetPromise()}
function C(a,b){a=a.toPrecision(Math.max(1,Math.min(21,Math.floor(b)))).toLowerCase();a.includes("e+")?a=a.replace("e+","\\times 10^{")+"}":a.includes("e")&&(a=a.replace("e","\\times 10^{")+"}");return a}new F;
