function f(a){switch(a){case "carbon-dioxide":return"CO_2";case "freon-12":return"CCl_2F_2"}}const g=[],k=[],l={plugins:{legend:!0},scales:{x:{beginAtZero:!1,title:{text:"Temperature [\u00b0C]",display:!0,font:{size:16}}},y:{beginAtZero:!0,title:{text:"sound speed [m/s]",display:!0,font:{size:14}}}}};let m=null;
function n(a,b){if(!a.g||b!=a.h){if((!a.g||b!=a.h)&&["carbon-dioxide","freon-12"].includes(b)){a.h=b;a:{switch(a.h){case "carbon-dioxide":b=12.0107+31.998;break a;case "freon-12":b=82.9167+37.996806;break a}b=void 0}a.g&&b==a.o||a.g&&b==a.o||Number.isNaN(b)||!Number.isFinite(b)||(a.o=b,b=8314/a.o,a.g&&b==a.l||a.g&&b==a.l||Number.isNaN(b)||!Number.isFinite(b)||(a.l=b,p(a),q(a),r(a),t(a),u(a),v(a)),w(a),r(a));a:{switch(a.h){case "carbon-dioxide":b=1.3;break a;case "freon-12":b=1.139;break a}b=void 0}a.g&&
b==a.m||a.g&&b==a.m||Number.isNaN(b)||!Number.isFinite(b)||(a.m=b,p(a),q(a),a.H.innerHTML=`\\[ \\gamma=${a.m}\\ . \\]`,x(),t(a),u(a),v(a));b=a.h;var e=a.J;for(var c of e)c.innerHTML=b;c=a.I;a:{switch(a.h){case "carbon-dioxide":b="CO<sub>2</sub>";break a;case "freon-12":b="CCl<sub>2</sub>F<sub>2</sub>";break a}b=void 0}for(var d of c)d.innerHTML=b;d=a.h;c=f(d);b="";switch(d){case "carbon-dioxide":b="\\text{atomic mass of }C+2\\times\\text{atomic mass of }O";break;case "freon-12":b="\\text{atomic mass of }C+2\\times\\text{atomic mass of }Cl+2\\times\\text{atomic mass of }F"}a.O.innerHTML=
`\\[ \\hat{m}_{${c}} = ${b} \\]`;x();w(a);r(a)}a.C.value=`${a.h}`}}function y(a,b){if(!a.g||b!=a.i){if(!(a.g&&b==a.i||Number.isNaN(b))&&Number.isFinite(b)){b=Math.max(b,-50);b=Math.min(b,1E3);a.g&&(b=Math.min(b,a.j-1));a.i=b;p(a);b=a.i;var e=a.K;for(var c of e)c.innerHTML=`${b}`;c=a.L;b=`${a.i+273}`;for(const d of c)d.innerHTML=b;t(a);v(a)}a.u.value=`${a.i}`}}
function z(a,b){if(!a.g||b!=a.j){if(!(a.g&&b==a.j||Number.isNaN(b))&&Number.isFinite(b)){b=Math.max(b,-50);b=Math.min(b,1E3);a.g&&(b=Math.max(b,a.i+1));a.j=b;q(a);b=a.j;var e=a.M;for(var c of e)c.innerHTML=`${b}`;c=a.N;b=`${a.j+273}`;for(const d of c)d.innerHTML=b;u(a);v(a)}a.v.value=`${a.j}`}}function p(a){var b=Math.sqrt(a.m*a.l*(a.i+273));a.g&&b==a.A||a.g&&b==a.A||Number.isNaN(b)||!Number.isFinite(b)||(a.A=b,t(a))}
function q(a){var b=Math.sqrt(a.m*a.l*(a.j+273));a.g&&b==a.B||a.g&&b==a.B||Number.isNaN(b)||!Number.isFinite(b)||(a.B=b,u(a))}function w(a){var b=a.h;const e=f(b);let c="";switch(b){case "carbon-dioxide":c="12.0107+2\\times15.999";break;case "freon-12":c="12.0107+2\\times35.453+2\\times18.998"}a.P.innerHTML=`\\[ \\hat{m}_{${e}}=${c}=${B(a.o)}\\,\\text{kg/kmol}\\ . \\]`;x()}
function r(a){var b=a.l;a.D.innerHTML=`\\[ R=\\frac{R_{u}}{\\hat{m}_{${f(a.h)}}}=\\frac{${8314}}{${B(a.o)}}=${B(b)}\\,\\text{J/kg-K}\\ . \\]`;x()}function t(a){var b=a.m,e=a.l,c=a.i,d=a.A;c+=273;a.F.innerHTML=`\\[ \\boxed{a=\\sqrt{${b}\\times${B(e)}\\times${c}}=${B(d)}\\,\\text{m/s}}\\ . \\]`;x()}function u(a){var b=a.m,e=a.l,c=a.j,d=a.B;c+=273;a.G.innerHTML=`\\[ \\boxed{a=\\sqrt{${b}\\times${B(e)}\\times${c}}=${B(d)}\\,\\text{m/s}}\\ . \\]`;x()}
function v(a){var b=a.m,e=a.l,c=a.i,d=a.R;a=(a.j-c)/500;for(let h=0;h<501;h++){const A=c+h*a;g[h]=Math.round(A*100)/100;k[h]=Math.sqrt(b*e*(A+273))}m==null&&(m=new Chart(d,{type:"line",data:{labels:g,datasets:[{label:"sound speed",data:k,borderWidth:4,pointStyle:!1,cubicInterpolationMode:"monotone"}]},options:l}));m.update()}
class C{constructor(){this.g=!1;this.C=document.getElementById("gases");this.C.addEventListener("change",()=>n(this,this.C.value));this.u=document.getElementById("T1");this.u.addEventListener("change",()=>y(this,parseFloat(this.u.value)));this.u.step="1";this.u.min="-50";this.u.max="1000";this.v=document.getElementById("T2");this.v.addEventListener("change",()=>z(this,parseFloat(this.v.value)));this.v.step="1";this.v.min="-50";this.v.max="1000";this.J=document.getElementsByClassName("gas-name");this.I=
document.getElementsByClassName("gas-formula");this.K=document.getElementsByClassName("given-T1");this.L=document.getElementsByClassName("given-T1K");this.M=document.getElementsByClassName("given-T2");this.N=document.getElementsByClassName("given-T2K");this.O=document.getElementById("molar-eqn");this.P=document.getElementById("molar-out");this.D=document.getElementById("R-out");this.H=document.getElementById("gamma-out");this.F=document.getElementById("a1-out");this.G=document.getElementById("a2-out");
this.R=document.getElementById("plot");this.h="carbon-dioxide";this.i=20;this.j=600;this.o=44;this.l=188.9;this.m=1.3;this.A=268.2;this.B=463;n(this,this.h);y(this,this.i);z(this,this.j);this.g=!0}}function x(){typeof MathJax!="undefined"&&MathJax.typesetPromise&&MathJax.typesetPromise()}function B(a){a=a.toPrecision(6).toLowerCase();a.includes("e+")?a=a.replace("e+","\\times 10^{")+"}":a.includes("e")&&(a=a.replace("e","\\times 10^{")+"}");return a}new C;
