function c(a,b){a.g&&b==a.u||(a.g&&b==a.u||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,1),b=Math.min(b,500),a.u=b,d(a),e(a)),a.A.value=`${a.u}`)}function f(a,b){a.g&&b==a.i||(a.g&&b==a.i||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,101),b=Math.min(b,200),a.i=b,g(a,a.i*1E3/(287*(a.h+273))),d(a),h(a),e(a)),a.v.value=`${a.i}`)}
function k(a,b){a.g&&b==a.h||(a.g&&b==a.h||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,-10),b=Math.min(b,100),a.h=b,g(a,a.i*1E3/(287*(a.h+273))),h(a),a.G.innerHTML=`\\( T_{2}=T_{1}=${a.h+273}\\,\\text{K} \\)`,l(),m(a),n(a,a.l/287/(a.h+273))),a.C.value=`${a.h}`)}function p(a,b){a.g&&b==a.m||(a.g&&b==a.m||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,1),b=Math.min(b,500),a.m=b,a.P.innerText=`${a.m}`,d(a),e(a)),a.B.value=`${a.m}`)}
function d(a){var b=a.u;var r=a.m;b=a.i*1E3+a.j/2*(b*b-r*r);a.g&&b==a.l||a.g&&b==a.l||Number.isNaN(b)||!Number.isFinite(b)||(a.l=b,e(a),a.K.innerHTML=`$$\\boxed{\\left.p_{2}\\right|_{\\text{incomp.}}=${(a.l/1E3).toFixed(4)}\\,\\text{kPa}}$$`,l(),m(a),n(a,a.l/287/(a.h+273)))}function g(a,b){a.g&&b==a.j||a.g&&b==a.j||Number.isNaN(b)||!Number.isFinite(b)||(a.j=b,d(a),h(a),a.O.innerHTML=`\\(\\rho=${a.j.toFixed(4)}\\,\\text{kg/m}^3\\)`,l(),e(a),b=a.j,q(a,(b-a.o)/b*100),t(a))}
function h(a){a.J.innerHTML="\\[\n"+`\\rho=\\rho_{1}=\\frac{p_{1}}{R\\,T_{1}}=\\frac{${a.i}\\times10^{3}}{287\\times\\left(${a.h}+273\\right)}=${a.j.toFixed(4)}\\,\\text{kg/m}^{3}`+"\n\\]";l()}function e(a){a.I.innerHTML=`$$p_{2}=${a.i}\\times10^{3}+\\frac{${a.j.toFixed(4)}}{2}\\left(${a.u}^{2}-${a.m}^{2}\\right) = ${a.l.toFixed(2)}\\,\\text{Pa}$$`;l()}function m(a){a.M.innerHTML=`$$\\rho=\\frac{p_{2}}{R\\,T_{2}}=\\frac{${a.l.toFixed(2)}}{287\\times ${a.h+273}}$$`;l()}
function n(a,b){a.g&&b==a.o||a.g&&b==a.o||Number.isNaN(b)||!Number.isFinite(b)||(a.o=b,a.N.innerHTML=`$$\\boxed{\\left.\\rho\\right|_{T=\\text{constant}}=${a.o.toFixed(4)}\\,\\text{kg/m}^{3}}$$`,l(),b=a.j,q(a,(b-a.o)/b*100),t(a))}
function q(a,b){a.g&&b==a.D||a.g&&b==a.D||Number.isNaN(b)||!Number.isFinite(b)||(a.D=b,t(a),b=Math.abs(a.D)>5?"Based on this comparison, it is clear that the <u><strong>use of Bernoulli's equation is not justified,</strong></u> as in an incompressible flow (with no heat transfer) the temperature variations are negligible. Therefore, the density calculated with this assumption must closely match with the result of Bernoulli's equation if the flow is indeed incompressible.":"Based on this comparison, it is clear that the <u><strong>use of Bernoulli's equation is justified,</strong></u> as in an incompressible flow (with no heat transfer) the temperature variations are negligible. The density calculated with this assumption closely match with the result of Bernoulli's equation therefore the flow can be assumed to be incompressible.",
a.g&&b==a.F||a.g&&b==a.F||(a.F=b,a.H.innerHTML=a.F))}function t(a){const b=`${a.j.toFixed(4)}`;a.L.innerHTML=`$$= \\frac{${b} - ${`${a.o.toFixed(4)}`}}{${b}}\\times 100 = ${`${a.D.toFixed(2)}`}\\%$$`;l()}
class u{constructor(){this.g=!1;this.A=document.getElementById("q-v1");this.A.addEventListener("change",()=>c(this,parseInt(this.A.value,10)));this.A.step="1";this.A.min="1";this.A.max="500";this.v=document.getElementById("q-p1");this.v.addEventListener("change",()=>f(this,parseInt(this.v.value,10)));this.v.step="1";this.v.min="101";this.v.max="200";this.C=document.getElementById("q-T1");this.C.addEventListener("change",()=>k(this,parseInt(this.C.value,10)));this.C.step="1";this.C.min="-10.0";this.C.max=
"100";this.B=document.getElementById("q-v2");this.B.addEventListener("change",()=>p(this,parseInt(this.B.value,10)));this.B.step="1";this.B.min="1";this.B.max="500";this.P=document.getElementById("qo-v2");this.J=document.getElementById("eq-rho");this.O=document.getElementById("rho-value");this.I=document.getElementById("eq-p2");this.K=document.getElementById("p2-boxed");this.G=document.getElementById("T2T1-value");this.M=document.getElementById("rhoT-const");this.N=document.getElementById("rhoT-const-boxed");
this.L=document.getElementById("percent-change-out");this.H=document.getElementById("conclusion-out");this.u=30;this.i=120;this.h=10;this.m=250;this.D=this.o=this.l=this.j=0;this.F="";c(this,this.u);f(this,this.i);k(this,this.h);p(this,this.m);this.g=!0}}function l(){typeof MathJax!="undefined"?MathJax.typesetPromise():console.log("MathJax not loaded yet!")}new u;
