function d(a,b){if(!a.g||b!=a.m){if(!(a.g&&b==a.m||Number.isNaN(b))&&Number.isFinite(b)){b=Math.max(b,1);b=Math.min(b,100);a.m=b;b=8314/a.m;a.g&&b==a.o||a.g&&b==a.o||Number.isNaN(b)||!Number.isFinite(b)||(a.o=b,b=a.l,f(a,b*a.o/(b-1)),h(a),k(a));b=a.m;var c=a.S;for(const e of c)e.innerText=`${b}`;h(a)}a.C.value=`${a.m}`}}
function l(a,b){a.g&&b==a.l||(a.g&&b==a.l||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,1.01),b=Math.min(b,1.99),a.l=b,b=a.l,f(a,b*a.o/(b-1)),a.R.innerText=`${a.l}`,k(a)),a.B.value=`${a.l}`)}function m(a,b){a.g&&b==a.j||(a.g&&b==a.j||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,.1),b=Math.min(b,1E3),a.j=b,n(a),a.P.innerText=`${a.j}`,p(a),q(a)),a.A.value=`${a.j}`)}
function r(a,b){a.g&&b==a.h||(a.g&&b==a.h||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,-50),b=Math.min(b,500),a.h=b,n(a),a.L.innerText=`${a.h}`,a.M.innerText=`${a.h+273}`,p(a),q(a)),a.D.value=`${a.h}`)}function t(a,b){a.g&&b==a.i||(a.g&&b==a.i||Number.isNaN(b)||!Number.isFinite(b)||(b=Math.max(b,-50),b=Math.min(b,500),a.i=b,n(a),a.N.innerText=`${a.i}`,a.O.innerText=`${a.i+273}`,p(a),q(a)),a.v.value=`${a.i}`)}
function n(a){var b=a.j;b=b*b+2*a.u*(a.h-a.i);b=b<=0?0:Math.sqrt(b);a.g&&b==a.F||a.g&&b==a.F||Number.isNaN(b)||!Number.isFinite(b)||(a.F=b,a.I.innerHTML=`\\[ \\boxed{V_{2}= ${u(a.F)}\\,\\text{m/s}}\\ . \\]`,v())}function f(a,b){a.g&&b==a.u||a.g&&b==a.u||Number.isNaN(b)||!Number.isFinite(b)||(a.u=b,n(a),k(a),p(a),q(a))}function h(a){a.G.innerHTML=`\\[ R=\\frac{R_{u}}{\\hat{m}}=\\frac{${8314}}{${a.m}}=${u(a.o)}\\,\\text{J/kg-K} \\]`;v()}
function k(a){var b=a.l,c=a.u;a.J.innerHTML=`\\[ c_{p}=\\frac{\\gamma\\,R}{\\gamma-1}=\\frac{${b}\\times${u(a.o)}}{${b}-1}= ${u(c)}\\,\\text{J/kg-K} \\]`;v()}function p(a){var b=a.u,c=a.h,e=a.j,g=a.i;c+=273;g+=273;a.K.innerHTML=`\\[ ${u(b)}\\times${c}+\\frac{${e}^{2}}{2}+\\cancelto{\\text{adiabatic}}{\\frac{\\dot{q}}{\\dot{m}}}=${u(b)}\\times${g}+\\frac{V_{2}^{2}}{2} \\]`;v()}
function q(a){var b=a.u,c=a.h,e=a.j,g=a.i;c+=273;g+=273;a.H.innerHTML=`\\[ V_{2}=\\sqrt{${e}^{2}+2\\times${u(b)}\\times\\left(${c}-${g}\\right)} \\]`;v()}
class w{constructor(){this.g=!1;this.C=document.getElementById("molar");this.C.addEventListener("change",()=>d(this,parseFloat(this.C.value)));this.C.step="0.01";this.C.min="1";this.C.max="100";this.B=document.getElementById("gamma");this.B.addEventListener("change",()=>l(this,parseFloat(this.B.value)));this.B.step="0.01";this.B.min="1.01";this.B.max="1.99";this.A=document.getElementById("V1");this.A.addEventListener("change",()=>m(this,parseFloat(this.A.value)));this.A.step="0.1";this.A.min="0.1";
this.A.max="1000";this.D=document.getElementById("T1");this.D.addEventListener("change",()=>r(this,parseFloat(this.D.value)));this.D.step="0.1";this.D.min="-50";this.D.max="500";this.v=document.getElementById("T2");this.v.addEventListener("change",()=>t(this,parseFloat(this.v.value)));this.v.step="0.1";this.v.min="-50";this.v.max="500";this.R=document.getElementById("given-gamma");this.S=document.getElementsByClassName("given-molar");this.P=document.getElementById("given-V1");this.L=document.getElementById("given-T1");
this.N=document.getElementById("given-T2");this.M=document.getElementById("given-T1K");this.O=document.getElementById("given-T2K");this.G=document.getElementById("R-out");this.J=document.getElementById("cp-out");this.K=document.getElementById("energy-eqn");this.H=document.getElementById("V2-eqn");this.I=document.getElementById("V2-out");this.m=4;this.l=1.67;this.j=180;this.h=10;this.i=-10;this.o=2078.5;this.u=5180.7;this.F=489.5;d(this,this.m);l(this,this.l);m(this,this.j);r(this,this.h);t(this,this.i);
this.g=!0}}function v(){typeof MathJax!="undefined"&&MathJax.typesetPromise()}function u(a){a=a.toPrecision(6).toLowerCase();a.includes("e+")?a=a.replace("e+","\\times 10^{")+"}":a.includes("e")&&(a=a.replace("e","\\times 10^{")+"}");return a}new w;
